/**
 * Seed script for Red Gulch and buildings
 */
const mongoose = require('mongoose');

async function seed() {
  await mongoose.connect('mongodb://localhost:27017/desperados-dev');
  console.log('Connected to MongoDB');

  // Define Location model
  const LocationSchema = new mongoose.Schema({}, { strict: false });
  const Location = mongoose.model('Location', LocationSchema);

  // Location IDs
  const LOCATION_IDS = {
    RED_GULCH: new mongoose.Types.ObjectId('6501a0000000000000000001'),
    THE_FRONTERA: new mongoose.Types.ObjectId('6501a0000000000000000002'),
    WHISKEY_BEND: new mongoose.Types.ObjectId('6501a000000000000000000c'),
  };

  // Red Gulch location data
  const redGulch = {
    _id: LOCATION_IDS.RED_GULCH,
    name: 'Red Gulch',
    description: 'The largest settler town in Sangre Territory, built in a canyon mouth where industry meets the frontier. Upper Town houses the wealthy elite while Lower Town thrums with saloons, shops, and the desperate hopes of prospectors.',
    shortDescription: 'Settler capital and boomtown',
    type: 'settlement',
    region: 'town',
    icon: '🏘️',
    atmosphere: 'The dusty streets buzz with activity. Piano music drifts from saloons, hammers ring from the blacksmith, and the constant murmur of commerce fills the air.',
    availableActions: [],
    availableCrimes: [],
    jobs: [],
    shops: [],
    npcs: [],
    connections: [
      { targetLocationId: LOCATION_IDS.THE_FRONTERA.toString(), travelTime: 0, energyCost: 10, description: 'South to The Frontera' },
      { targetLocationId: LOCATION_IDS.WHISKEY_BEND.toString(), travelTime: 0, energyCost: 15, description: 'South to Whiskey Bend' }
    ],
    dangerLevel: 3,
    factionInfluence: { settlerAlliance: 80, nahiCoalition: 5, frontera: 15 },
    isUnlocked: true,
    isHidden: false
  };

  // Delete existing and insert Red Gulch
  await Location.deleteMany({});
  await Location.create(redGulch);
  console.log('Created Red Gulch settlement');

  // Building IDs for Red Gulch
  const BUILDING_IDS = {
    GOLDEN_SPUR_SALOON: new mongoose.Types.ObjectId('6502a0000000000000000001'),
    SHERIFF_OFFICE: new mongoose.Types.ObjectId('6502a0000000000000000002'),
    MINERS_SUPPLY: new mongoose.Types.ObjectId('6502a0000000000000000003'),
    RED_GULCH_BANK: new mongoose.Types.ObjectId('6502a0000000000000000004'),
    IRON_JAKES_FORGE: new mongoose.Types.ObjectId('6502a0000000000000000005'),
    DUSTY_ROSE_HOTEL: new mongoose.Types.ObjectId('6502a0000000000000000006'),
    TELEGRAPH_OFFICE: new mongoose.Types.ObjectId('6502a0000000000000000007'),
    CHURCH: new mongoose.Types.ObjectId('6502a0000000000000000008'),
    DOCTORS_OFFICE: new mongoose.Types.ObjectId('6502a0000000000000000009'),
    LIVERY_STABLE: new mongoose.Types.ObjectId('6502a000000000000000000a'),
    MINERS_GUILD: new mongoose.Types.ObjectId('6502a000000000000000000b'),
    ASSAY_OFFICE: new mongoose.Types.ObjectId('6502a000000000000000000c'),
    RAILROAD_OFFICE: new mongoose.Types.ObjectId('6502a000000000000000000d'),
    GAZETTE_OFFICE: new mongoose.Types.ObjectId('6502a000000000000000000e'),
    GOLDEN_PHOENIX: new mongoose.Types.ObjectId('6502a000000000000000000f'),
  };

  // Red Gulch buildings
  const buildings = [
    {
      _id: BUILDING_IDS.GOLDEN_SPUR_SALOON,
      name: 'The Golden Spur Saloon',
      description: 'The heart of Red Gulch nightlife, where miners spend their earnings and secrets flow as freely as whiskey.',
      shortDescription: 'Main saloon and gathering place',
      type: 'saloon',
      region: 'town',
      parentId: LOCATION_IDS.RED_GULCH,
      tier: 3,
      dominantFaction: 'settler',
      icon: '🍺',
      operatingHours: { open: 10, close: 2 },
      dangerLevel: 3,
      factionInfluence: { settlerAlliance: 70, nahiCoalition: 10, frontera: 20 },
      isUnlocked: true,
      isHidden: false,
      jobs: [],
      shops: [],
      npcs: [],
      connections: [],
      availableActions: [],
      availableCrimes: []
    },
    {
      _id: BUILDING_IDS.SHERIFF_OFFICE,
      name: "Sheriff's Office",
      description: 'Law and order in Red Gulch. Marshal Kane Blackwood keeps the peace, but corruption runs deep.',
      shortDescription: 'Town jail and law enforcement',
      type: 'sheriff_office',
      region: 'town',
      parentId: LOCATION_IDS.RED_GULCH,
      tier: 3,
      dominantFaction: 'settler',
      icon: '⭐',
      operatingHours: { open: 0, close: 24 },
      dangerLevel: 2,
      isUnlocked: true,
      isHidden: false,
      jobs: [],
      shops: [],
      npcs: [],
      connections: [],
      availableActions: [],
      availableCrimes: [],
      factionInfluence: { settlerAlliance: 90, nahiCoalition: 5, frontera: 5 }
    },
    {
      _id: BUILDING_IDS.MINERS_SUPPLY,
      name: "Miner's Supply Co.",
      description: 'Everything a prospector needs, from picks to pans. Run by the Henderson family since the first gold strike.',
      shortDescription: 'General store and mining supplies',
      type: 'general_store',
      region: 'town',
      parentId: LOCATION_IDS.RED_GULCH,
      tier: 3,
      dominantFaction: 'settler',
      icon: '🏪',
      operatingHours: { open: 7, close: 19 },
      dangerLevel: 1,
      isUnlocked: true,
      isHidden: false,
      jobs: [],
      shops: [],
      npcs: [],
      connections: [],
      availableActions: [],
      availableCrimes: [],
      factionInfluence: { settlerAlliance: 80, nahiCoalition: 10, frontera: 10 }
    },
    {
      _id: BUILDING_IDS.RED_GULCH_BANK,
      name: 'Red Gulch Bank & Trust',
      description: "The heavily guarded repository for the town's gold. Rumored to hold millions in the vault.",
      shortDescription: 'Bank and gold repository',
      type: 'bank',
      region: 'town',
      parentId: LOCATION_IDS.RED_GULCH,
      tier: 3,
      dominantFaction: 'settler',
      icon: '🏦',
      operatingHours: { open: 9, close: 17 },
      dangerLevel: 2,
      isUnlocked: true,
      isHidden: false,
      jobs: [],
      shops: [],
      npcs: [],
      connections: [],
      availableActions: [],
      availableCrimes: [],
      factionInfluence: { settlerAlliance: 95, nahiCoalition: 0, frontera: 5 }
    },
    {
      _id: BUILDING_IDS.IRON_JAKES_FORGE,
      name: "Iron Jake's Forge",
      description: 'The ring of hammer on anvil echoes through town. Jake forges everything from horseshoes to weapons.',
      shortDescription: 'Blacksmith and weapon crafting',
      type: 'blacksmith',
      region: 'town',
      parentId: LOCATION_IDS.RED_GULCH,
      tier: 3,
      dominantFaction: 'settler',
      icon: '⚒️',
      operatingHours: { open: 6, close: 20 },
      dangerLevel: 1,
      isUnlocked: true,
      isHidden: false,
      jobs: [],
      shops: [],
      npcs: [],
      connections: [],
      availableActions: [],
      availableCrimes: [],
      factionInfluence: { settlerAlliance: 75, nahiCoalition: 15, frontera: 10 }
    },
    {
      _id: BUILDING_IDS.DUSTY_ROSE_HOTEL,
      name: 'The Dusty Rose Hotel',
      description: 'The finest establishment in Red Gulch. Clean rooms, hot baths, and discretion for those who can afford it.',
      shortDescription: 'Premier hotel and lodging',
      type: 'hotel',
      region: 'town',
      parentId: LOCATION_IDS.RED_GULCH,
      tier: 3,
      dominantFaction: 'settler',
      icon: '🏨',
      operatingHours: { open: 0, close: 24 },
      dangerLevel: 1,
      isUnlocked: true,
      isHidden: false,
      jobs: [],
      shops: [],
      npcs: [],
      connections: [],
      availableActions: [],
      availableCrimes: [],
      factionInfluence: { settlerAlliance: 80, nahiCoalition: 5, frontera: 15 }
    },
    {
      _id: BUILDING_IDS.TELEGRAPH_OFFICE,
      name: 'Western Union Telegraph',
      description: 'Connect to the outside world. News, money transfers, and urgent messages all pass through here.',
      shortDescription: 'Telegraph and communication',
      type: 'telegraph_office',
      region: 'town',
      parentId: LOCATION_IDS.RED_GULCH,
      tier: 3,
      dominantFaction: 'settler',
      icon: '📨',
      operatingHours: { open: 8, close: 18 },
      dangerLevel: 1,
      isUnlocked: true,
      isHidden: false,
      jobs: [],
      shops: [],
      npcs: [],
      connections: [],
      availableActions: [],
      availableCrimes: [],
      factionInfluence: { settlerAlliance: 85, nahiCoalition: 5, frontera: 10 }
    },
    {
      _id: BUILDING_IDS.CHURCH,
      name: 'First Methodist Church',
      description: 'A beacon of faith in the wilderness. Reverend Thomas offers guidance and sanctuary to all.',
      shortDescription: 'Church and community center',
      type: 'church',
      region: 'town',
      parentId: LOCATION_IDS.RED_GULCH,
      tier: 3,
      dominantFaction: 'settler',
      icon: '⛪',
      operatingHours: { open: 6, close: 21 },
      dangerLevel: 1,
      isUnlocked: true,
      isHidden: false,
      jobs: [],
      shops: [],
      npcs: [],
      connections: [],
      availableActions: [],
      availableCrimes: [],
      factionInfluence: { settlerAlliance: 90, nahiCoalition: 5, frontera: 5 }
    },
    {
      _id: BUILDING_IDS.DOCTORS_OFFICE,
      name: "Dr. Chen's Medical Office",
      description: 'Healing hands in a rough town. Dr. Chen treats bullet wounds and fever alike.',
      shortDescription: 'Medical care and pharmacy',
      type: 'doctors_office',
      region: 'town',
      parentId: LOCATION_IDS.RED_GULCH,
      tier: 3,
      dominantFaction: 'settler',
      icon: '🏥',
      operatingHours: { open: 8, close: 20 },
      dangerLevel: 1,
      isUnlocked: true,
      isHidden: false,
      jobs: [],
      shops: [],
      npcs: [],
      connections: [],
      availableActions: [],
      availableCrimes: [],
      factionInfluence: { settlerAlliance: 60, nahiCoalition: 30, frontera: 10 }
    },
    {
      _id: BUILDING_IDS.LIVERY_STABLE,
      name: 'Red Rock Livery Stable',
      description: 'The best horses in the territory. Board your mount or buy a new one.',
      shortDescription: 'Horse sales and boarding',
      type: 'stables',
      region: 'town',
      parentId: LOCATION_IDS.RED_GULCH,
      tier: 3,
      dominantFaction: 'settler',
      icon: '🐎',
      operatingHours: { open: 5, close: 22 },
      dangerLevel: 1,
      isUnlocked: true,
      isHidden: false,
      jobs: [],
      shops: [],
      npcs: [],
      connections: [],
      availableActions: [],
      availableCrimes: [],
      factionInfluence: { settlerAlliance: 70, nahiCoalition: 20, frontera: 10 }
    },
    {
      _id: BUILDING_IDS.MINERS_GUILD,
      name: "Miners' Guild Hall",
      description: 'Where prospectors stake claims and settle disputes. The Mining Consortium holds power here.',
      shortDescription: 'Mining claims and guild services',
      type: 'mining_office',
      region: 'town',
      parentId: LOCATION_IDS.RED_GULCH,
      tier: 3,
      dominantFaction: 'settler',
      icon: '⛏️',
      operatingHours: { open: 8, close: 17 },
      dangerLevel: 2,
      isUnlocked: true,
      isHidden: false,
      jobs: [],
      shops: [],
      npcs: [],
      connections: [],
      availableActions: [],
      availableCrimes: [],
      factionInfluence: { settlerAlliance: 85, nahiCoalition: 5, frontera: 10 }
    },
    {
      _id: BUILDING_IDS.ASSAY_OFFICE,
      name: "Morrison's Assay Office",
      description: "Get your ore tested and certified. Morrison knows his metals - and his customers' secrets.",
      shortDescription: 'Ore testing and valuation',
      type: 'assay_office',
      region: 'town',
      parentId: LOCATION_IDS.RED_GULCH,
      tier: 3,
      dominantFaction: 'settler',
      icon: '⚖️',
      operatingHours: { open: 9, close: 17 },
      dangerLevel: 1,
      isUnlocked: true,
      isHidden: false,
      jobs: [],
      shops: [],
      npcs: [],
      connections: [],
      availableActions: [],
      availableCrimes: [],
      factionInfluence: { settlerAlliance: 80, nahiCoalition: 10, frontera: 10 }
    },
    {
      _id: BUILDING_IDS.RAILROAD_OFFICE,
      name: 'Pacific Railroad Office',
      description: 'The railroad is coming to Red Gulch. Investors and opportunists circle like vultures.',
      shortDescription: 'Railroad planning and investment',
      type: 'railroad_station',
      region: 'town',
      parentId: LOCATION_IDS.RED_GULCH,
      tier: 3,
      dominantFaction: 'settler',
      icon: '🚂',
      operatingHours: { open: 9, close: 17 },
      dangerLevel: 2,
      isUnlocked: true,
      isHidden: false,
      jobs: [],
      shops: [],
      npcs: [],
      connections: [],
      availableActions: [],
      availableCrimes: [],
      factionInfluence: { settlerAlliance: 90, nahiCoalition: 0, frontera: 10 }
    },
    {
      _id: BUILDING_IDS.GAZETTE_OFFICE,
      name: 'The Red Gulch Gazette',
      description: 'Truth, rumor, and propaganda - all printed daily. Editor Martha Crane fears no one.',
      shortDescription: 'Newspaper and printing',
      type: 'newspaper_office',
      region: 'town',
      parentId: LOCATION_IDS.RED_GULCH,
      tier: 3,
      dominantFaction: 'settler',
      icon: '📰',
      operatingHours: { open: 6, close: 20 },
      dangerLevel: 1,
      isUnlocked: true,
      isHidden: false,
      jobs: [],
      shops: [],
      npcs: [],
      connections: [],
      availableActions: [],
      availableCrimes: [],
      factionInfluence: { settlerAlliance: 75, nahiCoalition: 10, frontera: 15 }
    },
    {
      _id: BUILDING_IDS.GOLDEN_PHOENIX,
      name: 'The Golden Phoenix',
      description: 'A Chinese establishment serving fine tea and dim sum. More happens in the back rooms than meets the eye.',
      shortDescription: 'Chinese restaurant and tea house',
      type: 'tea_house',
      region: 'town',
      parentId: LOCATION_IDS.RED_GULCH,
      tier: 3,
      dominantFaction: 'settler',
      icon: '🍵',
      operatingHours: { open: 11, close: 23 },
      dangerLevel: 2,
      isUnlocked: true,
      isHidden: false,
      jobs: [],
      shops: [],
      npcs: [],
      connections: [],
      availableActions: [],
      availableCrimes: [],
      factionInfluence: { settlerAlliance: 50, nahiCoalition: 20, frontera: 30 }
    }
  ];

  // Insert buildings
  await Location.insertMany(buildings);
  console.log('Created ' + buildings.length + ' buildings in Red Gulch');

  // Verify
  const count = await Location.countDocuments({});
  const bldgs = await Location.countDocuments({ parentId: LOCATION_IDS.RED_GULCH });
  console.log('Total locations: ' + count);
  console.log('Buildings with parentId=Red Gulch: ' + bldgs);

  await mongoose.disconnect();
  console.log('Done!');
}

seed().catch(console.error);
