/**
 * Whiskey Bend Buildings Seed Data
 *
 * Seeds the database with 12 buildings for Whiskey Bend,
 * a lawless gambling town where vice, sin, and outlaws thrive
 */

import mongoose from 'mongoose';
import { Location } from '../../models/Location.model';
import { LOCATION_IDS } from '../locations.seed';

// Building IDs for Whiskey Bend
export const WHISKEY_BEND_BUILDING_IDS = {
  LUCKY_STRIKE_SALOON: new mongoose.Types.ObjectId('6504a0000000000000000001'),
  SNAKE_EYES_CASINO: new mongoose.Types.ObjectId('6504a0000000000000000002'),
  CRIMSON_LANTERN: new mongoose.Types.ObjectId('6504a0000000000000000003'),
  RUSTY_SPUR_INN: new mongoose.Types.ObjectId('6504a0000000000000000004'),
  BLACK_MARKET_BAZAAR: new mongoose.Types.ObjectId('6504a0000000000000000005'),
  OUTLAWS_REST: new mongoose.Types.ObjectId('6504a0000000000000000006'),
  POISON_WELL_APOTHECARY: new mongoose.Types.ObjectId('6504a0000000000000000007'),
  BROKEN_BOTTLE_BRAWL_PIT: new mongoose.Types.ObjectId('6504a0000000000000000008'),
  SILVER_DOLLAR_BANK: new mongoose.Types.ObjectId('6504a0000000000000000009'),
  FRONTIER_GENERAL_STORE: new mongoose.Types.ObjectId('6504a000000000000000000a'),
  GOLDEN_HORSESHOE_THEATRE: new mongoose.Types.ObjectId('6504a000000000000000000b'),
  COFFIN_MAKER_SHOP: new mongoose.Types.ObjectId('6504a000000000000000000c'),
};

const whiskeyBendBuildings = [
  // ===== 1. LUCKY STRIKE SALOON =====
  {
    _id: WHISKEY_BEND_BUILDING_IDS.LUCKY_STRIKE_SALOON,
    name: 'Lucky Strike Saloon',
    description: 'The grandest gambling hall in Whiskey Bend, where fortunes are won and lost on the turn of a card. Madame Scarlett runs the establishment with velvet gloves hiding iron fists. The games are rigged, but proving it is deadly.',
    shortDescription: 'Main gambling hall and saloon',
    type: 'saloon',
    region: 'town',
    parentId: LOCATION_IDS.WHISKEY_BEND,
    tier: 4,
    dominantFaction: 'frontera',
    operatingHours: { open: 10, close: 6 },
    atmosphere: 'Chandeliers cast golden light on green felt tables. The air is thick with cigar smoke and desperation. Beautiful dealers shuffle cards with practiced grace while armed men watch from the shadows. Piano music mingles with the clink of coins and occasional gunshots.',
    npcs: [
      {
        id: 'madame-scarlett',
        name: 'Madame Scarlett',
        title: 'Saloon Owner',
        description: 'A stunning woman in crimson silk with emerald eyes that miss nothing. She built her empire on rigged games, blackmail, and knowing when to look the other way. Men underestimate her once.',
        personality: 'Cunning, seductive, and absolutely ruthless. Rewards loyalty generously and punishes betrayal creatively.',
        faction: 'FRONTERA',
        dialogue: [
          'Welcome to the Lucky Strike, darling. Your money is safe here... for now.',
          'Every man has a price. I\'ve made a fortune knowing what it is.',
          'Cheating? How dare you. My games are merely... fortunate for the house.',
          'You look like someone with interesting secrets. I collect those.',
        ],
        isVendor: true,
        shopId: 'lucky-strike-shop',
        quests: ['collect-debt', 'eliminate-witness'],
      },
      {
        id: 'slick-fingers-pete',
        name: 'Slick Fingers Pete',
        title: 'Head Dealer',
        description: 'A thin man with hands faster than thought. He can deal from the bottom, palm cards, and mark decks without anyone noticing. He\'s been shot at seventeen times and stabbed twice.',
        personality: 'Nervous but professional. Loyal to Scarlett out of pure terror.',
        dialogue: [
          'Place your bets, gentlemen. The house always-- I mean, good luck!',
          'Card counting? Sir, I must ask you to leave. Permanently.',
          'I once saw Madame Scarlett smile. I still have nightmares.',
        ],
      },
    ],
    availableActions: ['gamble', 'high-stakes-poker', 'buy-drink', 'gather-rumors', 'hire-enforcer'],
    availableCrimes: ['Cheat at Cards', 'Pickpocket Drunk', 'Rob Poker Table'],
    jobs: [
      {
        id: 'card-dealer',
        name: 'Card Dealer',
        description: 'Deal poker and faro. Skim a little off the top if you\'re clever.',
        energyCost: 15,
        cooldownMinutes: 30,
        rewards: { goldMin: 20, goldMax: 35, xp: 25, items: [] },
        requirements: { minLevel: 3 },
      },
      {
        id: 'debt-collector',
        name: 'Debt Collection',
        description: 'Collect what\'s owed to the house. Break fingers if necessary.',
        energyCost: 20,
        cooldownMinutes: 45,
        rewards: { goldMin: 25, goldMax: 50, xp: 40, items: [] },
        requirements: { minLevel: 5 },
      },
    ],
    shops: [
      {
        id: 'lucky-strike-shop',
        name: 'Lucky Strike Bar',
        description: 'Fine whiskey and luxury goods.',
        shopType: 'general',
        items: [
          { itemId: 'kentucky-bourbon', name: 'Kentucky Bourbon', description: 'The good stuff', price: 10 },
          { itemId: 'cuban-cigar', name: 'Cuban Cigar', description: 'Imported luxury', price: 15 },
          { itemId: 'champagne', name: 'French Champagne', description: 'For winners', price: 25 },
          { itemId: 'marked-deck', name: 'Marked Deck', description: 'For private use only', price: 75, requiredLevel: 8 },
        ],
        buyMultiplier: 0.3,
      },
    ],
    secrets: [
      {
        id: 'rigged-games-evidence',
        name: 'Hidden Office',
        description: 'Behind a false wall in Madame Scarlett\'s office lies proof of decades of rigged games, bribes to lawmen, and blackmail material on half the territory\'s elite.',
        type: 'hidden_room',
        unlockCondition: {
          minReputation: 50,
          npcTrust: { npcId: 'madame-scarlett', level: 4 },
        },
        content: {
          actions: ['study-ledgers', 'copy-blackmail-files', 'access-vault'],
          npcs: [],
          dialogue: [
            'So you\'ve earned enough trust to see the real business. Welcome to the inner circle, darling.',
          ],
        },
      },
    ],
    connections: [],
    dangerLevel: 6,
    factionInfluence: { settlerAlliance: 30, nahiCoalition: 5, frontera: 65 },
    isUnlocked: true,
    isHidden: false,
  },

  // ===== 2. SNAKE EYES CASINO =====
  {
    _id: WHISKEY_BEND_BUILDING_IDS.SNAKE_EYES_CASINO,
    name: 'Snake Eyes Casino',
    description: 'Where the stakes are life and death. "Diamond" Dan McGraw runs high-stakes games in velvet-lined rooms. Men have lost their souls here, and some literally disappeared trying to welsh on debts.',
    shortDescription: 'High stakes gambling den',
    type: 'casino',
    region: 'town',
    parentId: LOCATION_IDS.WHISKEY_BEND,
    tier: 4,
    dominantFaction: 'frontera',
    operatingHours: { open: 18, close: 8 },
    atmosphere: 'The click of ivory dice on mahogany echoes through smoke-filled rooms. Men in expensive suits bet fortunes on a single roll. Armed guards in tuxedos ensure debts are always paid. The roulette wheel spins endlessly, a hypnotic red and black blur.',
    requirements: { minCriminalRep: 15 },
    npcs: [
      {
        id: 'diamond-dan',
        name: '"Diamond" Dan McGraw',
        title: 'Casino Owner',
        description: 'A flashy man dripping with jewels and danger. He wears a diamond-studded revolver and has used it. Every finger has a ring, his teeth are gold, and his smile is a shark\'s promise.',
        personality: 'Flamboyant and deadly. Loves spectacle and violence in equal measure. Respects bold players.',
        faction: 'FRONTERA',
        dialogue: [
          'Minimum bet is one hundred dollars, friend. Can\'t afford it? There\'s the door.',
          'I won this casino on a pair of sixes. Killed the previous owner with the same hand.',
          'You\'ve got stones coming in here. Let\'s see if you leave with them.',
          'Luck is for suckers. I deal in certainties.',
        ],
        quests: ['tournament-champion', 'eliminate-rival'],
      },
    ],
    availableActions: ['tournament-entry', 'high-roller-games', 'bet-on-fights', 'private-game'],
    availableCrimes: ['Fix Dice', 'Marked Cards', 'Rob Safe'],
    jobs: [
      {
        id: 'casino-security',
        name: 'Casino Security',
        description: 'Watch for cheaters and ensure debts are collected. Violently.',
        energyCost: 18,
        cooldownMinutes: 40,
        rewards: { goldMin: 30, goldMax: 55, xp: 35, items: [] },
        requirements: { minLevel: 7 },
      },
      {
        id: 'tournament-entry-job',
        name: 'Tournament Host',
        description: 'Organize and run high-stakes tournaments.',
        energyCost: 15,
        cooldownMinutes: 35,
        rewards: { goldMin: 25, goldMax: 45, xp: 30, items: [] },
        requirements: { minLevel: 5 },
      },
    ],
    shops: [
      {
        id: 'snake-eyes-shop',
        name: 'Casino Cage',
        description: 'Chips, tokens, and lucky charms.',
        shopType: 'general',
        items: [
          { itemId: 'casino-chips', name: 'Casino Chips ($100)', description: 'For high-stakes games', price: 100 },
          { itemId: 'lucky-dice', name: 'Lucky Dice', description: 'Blessed by a priest... probably', price: 50 },
          { itemId: 'loaded-dice', name: 'Loaded Dice', description: 'Don\'t get caught', price: 125, requiredLevel: 10 },
          { itemId: 'rabbit-foot', name: 'Genuine Rabbit\'s Foot', description: '+5% gambling luck', price: 75 },
        ],
        buyMultiplier: 0.4,
      },
    ],
    secrets: [
      {
        id: 'hidden-safe-room',
        name: 'The Vault',
        description: 'A reinforced room beneath the casino floor where the night\'s take is stored. Getting in requires bypassing three locks, two guards, and Diamond Dan\'s paranoia.',
        type: 'hidden_room',
        unlockCondition: {
          minReputation: 70,
          npcTrust: { npcId: 'diamond-dan', level: 4 },
        },
        content: {
          actions: ['access-vault', 'count-take', 'inspect-ledgers'],
          npcs: [],
          dialogue: [
            'You\'ve earned the right to see where the real money goes. Don\'t make me regret this.',
          ],
        },
      },
    ],
    connections: [],
    dangerLevel: 7,
    factionInfluence: { settlerAlliance: 25, nahiCoalition: 0, frontera: 75 },
    isUnlocked: true,
    isHidden: false,
  },

  // ===== 3. CRIMSON LANTERN =====
  {
    _id: WHISKEY_BEND_BUILDING_IDS.CRIMSON_LANTERN,
    name: 'The Crimson Lantern',
    description: 'An upscale brothel and entertainment house run by the brilliant Miss Ruby Valentine. More secrets are traded here than the black market. The girls are beautiful, the boys are handsome, and all of them are spies.',
    shortDescription: 'Brothel and information hub',
    type: 'entertainment',
    region: 'town',
    parentId: LOCATION_IDS.WHISKEY_BEND,
    tier: 4,
    dominantFaction: 'frontera',
    operatingHours: { open: 14, close: 6 },
    atmosphere: 'Red velvet and silk everywhere. Perfume mingles with opium smoke. Soft music plays while beautiful people entertain powerful clients. Every room has peepholes, every conversation is recorded, every secret is catalogued.',
    requirements: { minLevel: 3 },
    npcs: [
      {
        id: 'ruby-valentine',
        name: 'Miss Ruby Valentine',
        title: 'Madam',
        description: 'Devastatingly intelligent and hauntingly beautiful. She speaks five languages, reads Latin, and runs the most sophisticated intelligence network in the territory. Her girls and boys don\'t just entertain - they extract.',
        personality: 'Sophisticated, calculating, and fiercely protective of her people. Values information above gold.',
        faction: 'FRONTERA',
        dialogue: [
          'Welcome to the Lantern. All pleasures can be arranged... for a price.',
          'My clients tell me things they wouldn\'t confess to God. That makes me very valuable.',
          'Touch one of my people without permission and you\'ll disappear. Permanently.',
          'I don\'t sell bodies. I sell secrets. The entertainment is just... foreplay.',
        ],
        isVendor: false,
        quests: ['extract-information', 'blackmail-target', 'protect-establishment'],
      },
      {
        id: 'scarlet-lily',
        name: 'Scarlet Lily',
        title: 'Top Courtesan',
        description: 'The most expensive and skilled courtesan in the territory. She\'s extracted confessions from generals, politicians, and outlaws. A master of manipulation.',
        personality: 'Charming, witty, and completely mercenary. Loyal only to Ruby and herself.',
        dialogue: [
          'Tell me your secrets, darling. I\'m excellent at keeping them... for now.',
          'Men are so easy to read when they\'re distracted.',
          'I could tell you stories that would start wars. Sometimes I do.',
        ],
      },
    ],
    availableActions: ['gather-intelligence', 'buy-information', 'hire-spy', 'attend-entertainment'],
    availableCrimes: ['Blackmail', 'Extortion', 'Plant Evidence'],
    jobs: [
      {
        id: 'information-gathering',
        name: 'Information Gathering',
        description: 'Circulate, listen, and report. Every whisper has value.',
        energyCost: 12,
        cooldownMinutes: 30,
        rewards: { goldMin: 20, goldMax: 40, xp: 30, items: [] },
        requirements: { minLevel: 3 },
      },
      {
        id: 'protection-work',
        name: 'Protection Detail',
        description: 'Guard the girls and boys. Handle troublesome clients.',
        energyCost: 15,
        cooldownMinutes: 35,
        rewards: { goldMin: 25, goldMax: 45, xp: 35, items: [] },
        requirements: { minLevel: 5 },
      },
    ],
    shops: [],
    secrets: [
      {
        id: 'blackmail-files',
        name: 'The Archives',
        description: 'A secret room containing decades of blackmail material, surveillance notes, and compromising photographs of the territory\'s most powerful people. This room could topple empires.',
        type: 'hidden_room',
        unlockCondition: {
          minReputation: 80,
          npcTrust: { npcId: 'ruby-valentine', level: 5 },
        },
        content: {
          actions: ['study-files', 'copy-evidence', 'select-target'],
          npcs: [],
          dialogue: [
            'What you see here could destroy kingdoms. Use it wisely... or not at all.',
          ],
        },
      },
    ],
    connections: [],
    dangerLevel: 5,
    factionInfluence: { settlerAlliance: 35, nahiCoalition: 5, frontera: 60 },
    isUnlocked: true,
    isHidden: false,
  },

  // ===== 4. RUSTY SPUR INN =====
  {
    _id: WHISKEY_BEND_BUILDING_IDS.RUSTY_SPUR_INN,
    name: 'Rusty Spur Inn',
    description: 'A decrepit hotel where wanted men rent rooms by the hour and secrets are buried in every wall. Innkeeper Morton "Mort" Graves sees everything from his desk and remembers it all. The rooms smell of old tobacco and older sins.',
    shortDescription: 'Seedy hotel and hideout',
    type: 'hotel',
    region: 'town',
    parentId: LOCATION_IDS.WHISKEY_BEND,
    tier: 4,
    dominantFaction: 'frontera',
    operatingHours: { open: 0, close: 23 }, // 24/7
    atmosphere: 'Faded wallpaper peels from water-stained walls. Floorboards creak with every step. The smell of cheap whiskey and gunpowder pervades everything. Every room has bloodstains someone tried to scrub out. Mort watches from behind his desk like a vulture waiting for death.',
    npcs: [
      {
        id: 'mort-graves',
        name: 'Morton "Mort" Graves',
        title: 'Innkeeper',
        description: 'A skeletal man with sunken eyes who never sleeps. He\'s run this hotel for thirty years and seen every kind of sin. He forgets nothing, forgives nothing, and trades information like currency.',
        personality: 'Morbid, cynical, and unexpectedly helpful if you pay. Never lies but rarely tells the whole truth.',
        faction: 'FRONTERA',
        dialogue: [
          'Room\'s two dollars. Extra if you want clean sheets. More if you want privacy.',
          'I didn\'t see nothing. I never see nothing. Unless you make it worth my while.',
          'Three men died in Room 7 this month. Four dollars a night for that one.',
          'Someone was asking about you yesterday. Tall fellow. Carried a Remington. Want to know more?',
        ],
        isVendor: true,
        shopId: 'rusty-spur-shop',
      },
      {
        id: 'one-eyed-maisie',
        name: 'One-Eyed Maisie',
        title: 'Housekeeper',
        description: 'An old woman who lost an eye to a knife fight. She cleans the rooms, disposes of bodies, and knows where everything is hidden. She\'ll sell you out for a drink.',
        personality: 'Bitter, practical, and surprisingly spry for her age.',
        dialogue: [
          'Found another body this morning. Tuesdays are always busy.',
          'You want these sheets burned or just washed?',
          'I got information if you got coin.',
        ],
      },
    ],
    availableActions: ['rent-room', 'lay-low', 'send-message', 'hide-contraband', 'gather-gossip'],
    availableCrimes: ['Rob Guest', 'Pickpocket', 'Plant Evidence'],
    jobs: [
      {
        id: 'room-service',
        name: 'Room Service',
        description: 'Deliver food, drink, and messages. Don\'t ask questions.',
        energyCost: 10,
        cooldownMinutes: 20,
        rewards: { goldMin: 12, goldMax: 22, xp: 20, items: [] },
        requirements: { minLevel: 1 },
      },
      {
        id: 'message-running',
        name: 'Message Running',
        description: 'Carry discrete communications between criminals.',
        energyCost: 12,
        cooldownMinutes: 25,
        rewards: { goldMin: 15, goldMax: 28, xp: 25, items: [] },
        requirements: { minLevel: 2 },
      },
    ],
    shops: [
      {
        id: 'rusty-spur-shop',
        name: 'Front Desk Services',
        description: 'Lodging, supplies, and questionable items.',
        shopType: 'general',
        items: [
          { itemId: 'room-key', name: 'Room (1 Night)', description: 'Questionable bedding included', price: 2 },
          { itemId: 'cheap-whiskey', name: 'Rotgut Whiskey', description: 'Tastes like regret', price: 1 },
          { itemId: 'disguise-kit', name: 'Disguise Kit', description: 'Fake beard, glasses, hat', price: 50, requiredLevel: 5 },
          { itemId: 'forged-papers', name: 'Forged Documents', description: 'New identity, cash only', price: 125, requiredLevel: 8 },
        ],
        buyMultiplier: 0.5,
      },
    ],
    secrets: [
      {
        id: 'hidden-passages',
        name: 'Secret Passages',
        description: 'A network of passages between rooms and a tunnel leading to the alley. Perfect for escaping law enforcement or setting up ambushes. Mort charges extra for access.',
        type: 'hidden_room',
        unlockCondition: {
          minReputation: 40,
          npcTrust: { npcId: 'mort-graves', level: 3 },
        },
        content: {
          actions: ['quick-escape', 'spy-on-guests', 'ambush-setup'],
          npcs: [],
          dialogue: [
            'Passages been here since the place was built. Bootleggers used them during Prohibition. Now they\'re yours... for a price.',
          ],
        },
      },
    ],
    connections: [],
    dangerLevel: 6,
    factionInfluence: { settlerAlliance: 20, nahiCoalition: 5, frontera: 75 },
    isUnlocked: true,
    isHidden: false,
  },

  // ===== 5. BLACK MARKET BAZAAR =====
  {
    _id: WHISKEY_BEND_BUILDING_IDS.BLACK_MARKET_BAZAAR,
    name: 'Black Market Bazaar',
    description: 'A warehouse converted into a criminal marketplace. "Whisper" Chen controls the flow of stolen goods, contraband, and illegal items. If it\'s hot, he\'ll fence it. If it\'s banned, he\'ll sell it.',
    shortDescription: 'Illegal goods and fencing',
    type: 'black_market',
    region: 'town',
    parentId: LOCATION_IDS.WHISKEY_BEND,
    tier: 4,
    dominantFaction: 'frontera',
    operatingHours: { open: 20, close: 6 },
    atmosphere: 'Dim lanterns reveal crates of mysterious goods. Everything smells faintly of gunpowder and tobacco. Shadowy figures examine merchandise, speaking in hushed tones. Armed guards watch from the rafters. No questions asked, no names recorded.',
    requirements: { minCriminalRep: 20 },
    npcs: [
      {
        id: 'whisper-chen',
        name: '"Whisper" Chen',
        title: 'Fence Master',
        description: 'A mysterious Chinese man who never raises his voice above a whisper. He runs the most efficient fencing operation west of the Mississippi. Rumored to have connections to the Tong in San Francisco and the Frontera cartels.',
        personality: 'Calm, inscrutable, and absolutely professional. Values efficiency and discretion above all.',
        faction: 'FRONTERA',
        dialogue: [
          '*whisper* You bring goods? I give fair price. No names, no problems.',
          'Everything for sale. Everything has price. You buy or you sell?',
          '*whisper* I know you steal this. I don\'t care. You want gold or trade?',
          'Cartel want this tomorrow. You deliver, I pay double. You fail, I never know you.',
        ],
        isVendor: true,
        shopId: 'black-market-shop',
        quests: ['smuggle-contraband', 'fence-heist-goods'],
      },
      {
        id: 'three-finger-jake',
        name: 'Three-Finger Jake',
        title: 'Arms Dealer',
        description: 'Lost two fingers to a rifle misfire. Now sells stolen military weapons and foreign firearms. Has connections to corrupt quartermasters.',
        personality: 'Paranoid and aggressive. Quick to draw.',
        dialogue: [
          'Got repeaters fresh from the Army depot. Don\'t ask how.',
          'Chinese asked too many questions once. Emphasis on once.',
          'Every weapon has a history. You don\'t want to know most of them.',
        ],
      },
    ],
    availableActions: ['fence-goods', 'buy-contraband', 'special-order', 'hire-smuggler'],
    availableCrimes: ['Steal Contraband', 'Hijack Shipment', 'Rob Warehouse'],
    jobs: [
      {
        id: 'smuggling-run',
        name: 'Smuggling Run',
        description: 'Transport illegal goods across territory lines.',
        energyCost: 25,
        cooldownMinutes: 60,
        rewards: { goldMin: 40, goldMax: 75, xp: 50, items: [] },
        requirements: { minLevel: 8 },
      },
      {
        id: 'fence-operator',
        name: 'Fence Operation',
        description: 'Process and move stolen merchandise.',
        energyCost: 15,
        cooldownMinutes: 35,
        rewards: { goldMin: 25, goldMax: 45, xp: 35, items: [] },
        requirements: { minLevel: 5 },
      },
    ],
    shops: [
      {
        id: 'black-market-shop',
        name: 'Black Market Goods',
        description: 'Contraband, stolen items, and illegal weapons.',
        shopType: 'black_market',
        items: [
          { itemId: 'stolen-jewelry', name: 'Stolen Jewelry', description: 'Hot merchandise', price: 75 },
          { itemId: 'opium', name: 'Opium', description: 'Imported from China', price: 50, requiredLevel: 5 },
          { itemId: 'military-rifle', name: 'Stolen Army Rifle', description: 'Never been fired... recently', price: 200, requiredLevel: 10 },
          { itemId: 'nitro-glycerin', name: 'Nitro-Glycerin', description: 'Extremely unstable', price: 150, requiredLevel: 12 },
          { itemId: 'counterfeit-gold', name: 'Counterfeit Gold Bars', description: 'Fool most assayers', price: 300, requiredLevel: 15 },
        ],
        buyMultiplier: 0.7,
      },
    ],
    secrets: [
      {
        id: 'cartel-connections',
        name: 'Cartel Office',
        description: 'A secret room where Chen meets with Frontera cartel representatives. Contains shipping manifests for major smuggling operations and contacts throughout the territory.',
        type: 'hidden_room',
        unlockCondition: {
          minReputation: 75,
          npcTrust: { npcId: 'whisper-chen', level: 4 },
        },
        content: {
          actions: ['study-routes', 'contact-cartel', 'plan-operation'],
          npcs: [],
          dialogue: [
            '*whisper* You prove worthy. Now you see real business. Cartel respect efficiency. Show respect back.',
          ],
        },
      },
    ],
    connections: [],
    dangerLevel: 8,
    factionInfluence: { settlerAlliance: 10, nahiCoalition: 5, frontera: 85 },
    isUnlocked: true,
    isHidden: false,
  },

  // ===== 6. OUTLAW'S REST =====
  {
    _id: WHISKEY_BEND_BUILDING_IDS.OUTLAWS_REST,
    name: "Outlaw's Rest",
    description: 'The most dangerous building in Whiskey Bend. "One-Eye" Jack Raven runs it as neutral ground for outlaws to meet, plan heists, and recruit gang members. Walking in means accepting the outlaw code or dying.',
    shortDescription: 'Criminal hideout and planning den',
    type: 'hideout',
    region: 'town',
    parentId: LOCATION_IDS.WHISKEY_BEND,
    tier: 4,
    dominantFaction: 'frontera',
    operatingHours: { open: 22, close: 8 },
    atmosphere: 'Gun oil, tobacco, and old leather. Maps cover the walls with heist routes and bank layouts. Wanted posters serve as wallpaper, many featuring the current occupants. The air crackles with barely contained violence. Everyone here has killed, and most wear it proudly.',
    requirements: { minCriminalRep: 30, minLevel: 5 },
    npcs: [
      {
        id: 'one-eye-jack',
        name: '"One-Eye" Jack Raven',
        title: 'Legendary Outlaw',
        description: 'Lost his eye to a marshal\'s bullet in \'78. Killed that marshal and twelve others breaking out of prison. He\'s robbed more banks than anyone alive and survived three hangings. The most dangerous man in the territory.',
        personality: 'Cold, professional, and surprisingly honorable by outlaw standards. Respects competence and courage.',
        faction: 'FRONTERA',
        dialogue: [
          'You want in? Prove you got the stones. I don\'t work with amateurs.',
          'Lost my eye but kept my life. The marshal lost both. I call that a win.',
          'Every man here would sell his mother for gold. But they won\'t betray the code. Not twice.',
          'Planning a job that\'ll make us legends or corpses. You in?',
        ],
        quests: ['big-score-heist', 'recruit-gang-member', 'eliminate-rival-gang'],
      },
      {
        id: 'dynamite-doris',
        name: 'Dynamite Doris',
        title: 'Explosives Expert',
        description: 'A wild-eyed woman who lost three fingers learning her trade. She can blow any safe, vault, or train. She loves her work a little too much.',
        personality: 'Manic, brilliant, and probably insane. Treats explosives like children.',
        dialogue: [
          'Boom is the most beautiful word in any language.',
          'Want me to blow something? I\'ll blow ANYTHING.',
          'They call me crazy. I call myself an artist.',
        ],
      },
    ],
    availableActions: ['plan-heist', 'recruit-gang', 'study-targets', 'fence-major-scores'],
    availableCrimes: ['Bank Heist', 'Train Robbery', 'Assassination'],
    jobs: [
      {
        id: 'heist-planning',
        name: 'Heist Planning',
        description: 'Scout targets and plan elaborate robberies.',
        energyCost: 20,
        cooldownMinutes: 60,
        rewards: { goldMin: 35, goldMax: 70, xp: 60, items: [] },
        requirements: { minLevel: 10 },
      },
      {
        id: 'gang-recruitment',
        name: 'Gang Recruitment',
        description: 'Find skilled outlaws for upcoming jobs.',
        energyCost: 15,
        cooldownMinutes: 40,
        rewards: { goldMin: 25, goldMax: 50, xp: 40, items: [] },
        requirements: { minLevel: 7 },
      },
    ],
    shops: [],
    secrets: [
      {
        id: 'treasure-map',
        name: 'The Big Score',
        description: 'Jack\'s final job - a map to a gold shipment worth half a million dollars. He\'s been planning it for five years. Everyone who\'s seen the full plan is either dead or in on it.',
        type: 'hidden_room',
        unlockCondition: {
          minReputation: 90,
          npcTrust: { npcId: 'one-eye-jack', level: 5 },
        },
        content: {
          actions: ['study-plans', 'recruit-team', 'finalize-details'],
          npcs: ['dynamite-doris'],
          dialogue: [
            'This is it. The job that lets us retire rich or die famous. No middle ground.',
          ],
        },
      },
    ],
    connections: [],
    dangerLevel: 9,
    factionInfluence: { settlerAlliance: 5, nahiCoalition: 0, frontera: 95 },
    isUnlocked: true,
    isHidden: false,
  },

  // ===== 7. POISON WELL APOTHECARY =====
  {
    _id: WHISKEY_BEND_BUILDING_IDS.POISON_WELL_APOTHECARY,
    name: 'Poison Well Apothecary',
    description: 'Dr. Ezekiel Crane\'s medical practice and laboratory. He\'ll treat your wounds or create poisons to inflict them. His experiments with chemicals and "life restoration" have produced disturbing results.',
    shortDescription: 'Shady medicine and poisons',
    type: 'apothecary',
    region: 'town',
    parentId: LOCATION_IDS.WHISKEY_BEND,
    tier: 4,
    dominantFaction: 'frontera',
    operatingHours: { open: 0, close: 23 }, // 24/7
    atmosphere: 'Chemical smells overpower everything. Bubbling beakers and strange apparatus fill every surface. Preserved specimens float in jars - some human. The back room is locked and screams occasionally emanate from within. Dr. Crane works without sleeping, his eyes wild with manic energy.',
    npcs: [
      {
        id: 'dr-crane',
        name: 'Dr. Ezekiel Crane',
        title: 'Mad Doctor',
        description: 'A brilliant but unstable physician and chemist. He was expelled from medical school for "unethical experiments." He treats patients, brews poisons, and pursues his obsession with conquering death itself.',
        personality: 'Manic genius bordering on insanity. Brilliant but completely amoral. Views patients as experimental subjects.',
        faction: 'FRONTERA',
        dialogue: [
          'Poison or antidote? The difference is merely dosage, my friend!',
          'Death is not the end! It\'s merely... a temporary setback I\'m working to overcome.',
          'Your gunshot wound is fascinating. Mind if I take samples before treating it?',
          'The formula is nearly complete. Soon, soon, I\'ll prove them all wrong!',
        ],
        isVendor: true,
        shopId: 'poison-well-shop',
        quests: ['gather-specimens', 'test-formula'],
      },
      {
        id: 'nurse-agatha',
        name: 'Nurse Agatha',
        title: 'Assistant',
        description: 'A hollow-eyed woman who helps with surgeries and experiments. She\'s seen too much but can\'t leave. Some say she\'s as mad as the doctor now.',
        personality: 'Detached, traumatized, but grimly efficient.',
        dialogue: [
          'He needs fresh specimens. Preferably alive. Freshness matters.',
          'I used to pray for the souls we... work on. I stopped years ago.',
          'Don\'t ask about the screaming. You really don\'t want to know.',
        ],
      },
    ],
    availableActions: ['buy-medicine', 'buy-poison', 'heal', 'experimental-treatment'],
    availableCrimes: ['Steal Chemicals', 'Grave Robbing'],
    jobs: [
      {
        id: 'poison-brewing',
        name: 'Poison Brewing',
        description: 'Help create various toxins and chemical weapons.',
        energyCost: 15,
        cooldownMinutes: 35,
        rewards: { goldMin: 30, goldMax: 55, xp: 40, items: [] },
        requirements: { minLevel: 6 },
      },
      {
        id: 'experimental-testing',
        name: 'Experimental Subject',
        description: 'Test Dr. Crane\'s latest formulas. High risk, high reward.',
        energyCost: 20,
        cooldownMinutes: 60,
        rewards: { goldMin: 50, goldMax: 100, xp: 60, items: [] },
        requirements: { minLevel: 8 },
      },
    ],
    shops: [
      {
        id: 'poison-well-shop',
        name: 'Poison Well Apothecary',
        description: 'Medicine, poisons, and experimental tonics.',
        shopType: 'medicine',
        items: [
          { itemId: 'health-tonic', name: 'Health Tonic', description: 'Restores vitality... probably', price: 20 },
          { itemId: 'arsenic', name: 'Arsenic', description: 'Tasteless and deadly', price: 60, requiredLevel: 5 },
          { itemId: 'cobra-venom', name: 'Cobra Venom', description: 'Imported from India', price: 100, requiredLevel: 8 },
          { itemId: 'experimental-serum', name: 'Experimental Serum', description: 'Unknown effects', price: 150, requiredLevel: 10 },
          { itemId: 'laudanum', name: 'Laudanum', description: 'Opium tincture, highly addictive', price: 25 },
          { itemId: 'chloroform', name: 'Chloroform', description: 'For subduing targets', price: 75, requiredLevel: 7 },
        ],
        buyMultiplier: 0.5,
      },
    ],
    secrets: [
      {
        id: 'resurrection-formula',
        name: 'The Laboratory',
        description: 'Dr. Crane\'s secret lab where he conducts experiments on reanimation. Bodies in various states line tables. His "resurrection formula" has produced... things. Things that shouldn\'t exist.',
        type: 'hidden_room',
        unlockCondition: {
          minReputation: 60,
          npcTrust: { npcId: 'dr-crane', level: 4 },
        },
        content: {
          actions: ['study-formula', 'examine-specimens', 'assist-experiment'],
          npcs: ['nurse-agatha'],
          dialogue: [
            'The formula works! Well, they move. And scream. Still perfecting the "conscious thought" aspect...',
          ],
        },
      },
    ],
    connections: [],
    dangerLevel: 7,
    factionInfluence: { settlerAlliance: 15, nahiCoalition: 5, frontera: 80 },
    isUnlocked: true,
    isHidden: false,
  },

  // ===== 8. BROKEN BOTTLE BRAWL PIT =====
  {
    _id: WHISKEY_BEND_BUILDING_IDS.BROKEN_BOTTLE_BRAWL_PIT,
    name: 'Broken Bottle Brawl Pit',
    description: 'An underground fighting arena where men settle disputes with fists, knives, and sometimes guns. "Crusher" Carlotta Vega runs the bloodiest entertainment in the territory. Every fight is to submission or death.',
    shortDescription: 'Underground fighting arena',
    type: 'fighting_pit',
    region: 'town',
    parentId: LOCATION_IDS.WHISKEY_BEND,
    tier: 4,
    dominantFaction: 'frontera',
    operatingHours: { open: 20, close: 6 },
    atmosphere: 'The crowd roars around a sunken dirt pit stained brown with old blood. Oil lamps cast flickering shadows on eager faces. Money changes hands as bets fly. The smell of sweat, blood, and violence fills the cramped space. Fighters emerge from tunnels like gladiators to cheers or jeers.',
    requirements: { minLevel: 3 },
    npcs: [
      {
        id: 'crusher-carlotta',
        name: '"Crusher" Carlotta Vega',
        title: 'Former Champion',
        description: 'A muscular Mexican woman with scars covering her arms and face. She held the pit championship for three years before retiring undefeated. Now she runs the fights and won\'t hesitate to step back in if someone disrespects the pit.',
        personality: 'Tough, fair within the brutal rules, and respects fighters who show heart.',
        faction: 'FRONTERA',
        dialogue: [
          'Rules are simple: fight until one can\'t continue. Weapons allowed, magic isn\'t.',
          'I broke seventeen bones winning this pit. You think you got what it takes?',
          'Crowd wants blood. Don\'t disappoint them or you won\'t leave vertical.',
          'You fix fights in my pit, you fight me next. Nobody fixes fights against me.',
        ],
        quests: ['become-champion', 'investigate-fixed-fights'],
      },
      {
        id: 'knuckles-malone',
        name: 'Knuckles Malone',
        title: 'Current Champion',
        description: 'An Irish brawler with hands like sledgehammers. He\'s killed three men in the pit and crippled a dozen more. Some say he\'s taking a dive next week for the right price.',
        personality: 'Brutal and greedy. Loyal to money, not honor.',
        dialogue: [
          'You want a piece of the champ? Bring gold for the doc, you\'ll need him.',
          'I hit harder than anyone in this territory. Prove me wrong.',
          'Everything\'s for sale. Including this belt. Make me an offer.',
        ],
      },
    ],
    availableActions: ['enter-fight', 'bet-on-match', 'challenge-champion', 'watch-fights'],
    availableCrimes: ['Fix Fight', 'Poison Fighter', 'Rig Bets'],
    jobs: [
      {
        id: 'prize-fighting',
        name: 'Prize Fighting',
        description: 'Fight for money and glory in the pit.',
        energyCost: 25,
        cooldownMinutes: 60,
        rewards: { goldMin: 40, goldMax: 80, xp: 50, items: [] },
        requirements: { minLevel: 5 },
      },
      {
        id: 'betting-runner',
        name: 'Betting Runner',
        description: 'Collect and pay out bets. Skim carefully.',
        energyCost: 12,
        cooldownMinutes: 30,
        rewards: { goldMin: 20, goldMax: 40, xp: 25, items: [] },
        requirements: { minLevel: 3 },
      },
    ],
    shops: [
      {
        id: 'brawl-pit-shop',
        name: 'Fighter\'s Corner',
        description: 'Weapons and fighting gear.',
        shopType: 'weapons',
        items: [
          { itemId: 'brass-knuckles', name: 'Brass Knuckles', description: 'Pit legal', price: 25 },
          { itemId: 'fighting-knife', name: 'Fighting Knife', description: '8-inch blade', price: 35 },
          { itemId: 'sap-gloves', name: 'Sap Gloves', description: 'Lead-lined leather', price: 50, requiredLevel: 5 },
          { itemId: 'chain-whip', name: 'Chain Whip', description: 'For advanced fighters', price: 75, requiredLevel: 8 },
          { itemId: 'medical-kit', name: 'Fighter\'s Medical Kit', description: 'Patch yourself up', price: 40 },
        ],
        buyMultiplier: 0.4,
      },
    ],
    secrets: [
      {
        id: 'fixed-fight-schedule',
        name: 'Betting Office',
        description: 'A back room where certain fights are arranged in advance. The schedule shows which matches are fixed, who\'s taking dives, and how much the house makes from rigged bets.',
        type: 'hidden_room',
        unlockCondition: {
          minReputation: 55,
          npcTrust: { npcId: 'crusher-carlotta', level: 3 },
        },
        content: {
          actions: ['study-schedule', 'place-insider-bets', 'expose-corruption'],
          npcs: [],
          dialogue: [
            'Not all fights are honest. But you didn\'t hear that from me. Bet smart, stay quiet.',
          ],
        },
      },
    ],
    connections: [],
    dangerLevel: 8,
    factionInfluence: { settlerAlliance: 20, nahiCoalition: 5, frontera: 75 },
    isUnlocked: true,
    isHidden: false,
  },

  // ===== 9. THE SILVER DOLLAR BANK =====
  {
    _id: WHISKEY_BEND_BUILDING_IDS.SILVER_DOLLAR_BANK,
    name: 'The Silver Dollar Bank',
    description: 'The most solid brick building in Whiskey Bend, a fortress of financial security in a lawless town. Ezekiel Crane, a reformed outlaw turned banker, knows every debt and secret in the territory. His Gray Ledger holds more power than any gun.',
    shortDescription: 'Town bank and financial institution',
    type: 'bank',
    region: 'town',
    parentId: LOCATION_IDS.WHISKEY_BEND,
    tier: 4,
    dominantFaction: 'neutral',
    operatingHours: { open: 9, close: 17 },
    atmosphere: 'Heavy oak doors open into a marble-floored sanctuary of commerce. Polished brass fixtures gleam under gaslight. The massive vault door dominates one wall, a testament to security. Crane watches from his glass-walled office, his sharp eyes cataloging every transaction, every nervous glance, every secret carried through his doors.',
    npcs: [
      {
        id: 'ezekiel-crane',
        name: 'Ezekiel Crane',
        title: 'Bank President',
        description: 'A distinguished gentleman in an expensive suit, but his gun-hand calluses betray his outlaw past. He robbed banks for twenty years before buying this one with his final score. Now he runs it honestly... mostly. His Gray Ledger contains every debt, loan, and secret in Whiskey Bend.',
        personality: 'Shrewd, calculating, and ruthlessly neutral. He serves all factions equally and trusts none. Respects those who pay their debts.',
        faction: 'NEUTRAL',
        dialogue: [
          'I used to rob banks. Now I own one. The irony pays better than outlawry ever did.',
          'Every man in this town owes someone something. I simply keep the ledger.',
          'Your money is safe here. My reputation depends on it, and I killed men for less.',
          'A secret is just a loan waiting to be called in. Pay your debts, friend.',
          'I know what you owe, who you owe it to, and what happens if you don\'t pay. That information has value.',
        ],
        isVendor: false,
        quests: ['collect-outstanding-debt', 'secure-gold-shipment', 'investigate-embezzlement'],
      },
      {
        id: 'rebecca-thornton',
        name: 'Rebecca Thornton',
        title: 'Head Teller',
        description: 'A sharp-eyed young woman who notices everything. She counts coins faster than anyone and can spot a counterfeit bill at twenty paces. She reports everything to Crane, making her the second most informed person in town.',
        personality: 'Professional, observant, and quietly ambitious. Nothing escapes her notice.',
        faction: 'NEUTRAL',
        dialogue: [
          'Making a deposit or withdrawal, sir? We require proper identification.',
          'I notice things. It\'s my job. That gun wasn\'t there yesterday, those boots are new, and you\'re nervous. Why?',
          'Mr. Crane trusts me to know everything that happens in this bank. I don\'t disappoint.',
          'Counterfeit? Please. I can tell real silver from fake by the sound it makes on marble.',
        ],
      },
      {
        id: 'thomas-west',
        name: 'Thomas West',
        title: 'Security Captain',
        description: 'A former lawman who guards the bank with cold efficiency. Two armed deputies flank him at all times. He\'s killed three would-be robbers and wounded a dozen more.',
        personality: 'Vigilant, serious, and absolutely loyal to Crane. Never smiles, never relaxes.',
        dialogue: [
          'Keep your hands where I can see them. Bank policy.',
          'Try anything stupid and this scattergun will be the last thing you see.',
          'Mr. Crane pays me well to keep this place safe. I earn every dollar.',
        ],
      },
    ],
    availableActions: ['deposit-gold', 'withdraw-gold', 'take-loan', 'invest', 'safe-deposit-box'],
    availableCrimes: ['Case the Vault', 'Forge Documents', 'Attempt Robbery'],
    jobs: [
      {
        id: 'security-guard',
        name: 'Security Guard',
        description: 'Guard the bank from robbers and protect gold shipments.',
        energyCost: 15,
        cooldownMinutes: 40,
        rewards: { goldMin: 25, goldMax: 45, xp: 30, items: [] },
        requirements: { minLevel: 3 },
      },
      {
        id: 'vault-cleaner',
        name: 'Vault Cleaning',
        description: 'Clean and organize the vault. Don\'t touch anything you shouldn\'t.',
        energyCost: 8,
        cooldownMinutes: 20,
        rewards: { goldMin: 10, goldMax: 18, xp: 15, items: [] },
        requirements: { minLevel: 1 },
      },
      {
        id: 'ledger-audit',
        name: 'Ledger Audit',
        description: 'Audit financial records and track down discrepancies.',
        energyCost: 18,
        cooldownMinutes: 50,
        rewards: { goldMin: 35, goldMax: 65, xp: 50, items: [] },
        requirements: { minLevel: 8 },
      },
    ],
    shops: [],
    secrets: [
      {
        id: 'gray-ledger',
        name: 'The Gray Ledger',
        description: 'Crane\'s personal records of who owes whom in Whiskey Bend. Not just financial debts, but favors, secrets, and obligations. This information could topple the town\'s power structure or make you the richest person in the territory through strategic blackmail.',
        type: 'hidden_room',
        unlockCondition: {
          minReputation: 70,
          npcTrust: { npcId: 'ezekiel-crane', level: 4 },
        },
        content: {
          actions: ['study-debts', 'copy-ledger', 'blackmail-debtor', 'trade-information'],
          npcs: [],
          dialogue: [
            'Knowledge is the only currency that appreciates with time. Use this wisely, or it will destroy you.',
          ],
        },
      },
    ],
    connections: [],
    dangerLevel: 4,
    factionInfluence: { settlerAlliance: 35, nahiCoalition: 30, frontera: 35 },
    isUnlocked: true,
    isHidden: false,
  },

  // ===== 10. FRONTIER GENERAL STORE =====
  {
    _id: WHISKEY_BEND_BUILDING_IDS.FRONTIER_GENERAL_STORE,
    name: 'Frontier General Store',
    description: 'Hiram and Sarah Buckley\'s general store serves everyone in Whiskey Bend with practical goods and neutral service. Behind the cheerful merchant facade lies a dangerous secret - they hide people for the right price, no questions asked.',
    shortDescription: 'General goods and provisions',
    type: 'general_store',
    region: 'town',
    parentId: LOCATION_IDS.WHISKEY_BEND,
    tier: 4,
    dominantFaction: 'neutral',
    operatingHours: { open: 7, close: 20 },
    atmosphere: 'Shelves packed with everything from flour to firearms. The smell of leather, coffee, and tobacco fills the air. Hiram greets customers with a friendly smile while Sarah manages inventory with military precision. A trapdoor behind the counter leads somewhere the Buckleys don\'t discuss.',
    npcs: [
      {
        id: 'hiram-buckley',
        name: 'Hiram Buckley',
        title: 'Store Owner',
        description: 'A jovial middle-aged man with a ready smile and careful eyes. He\'s survived in Whiskey Bend for fifteen years by serving all sides and offending none. His neutrality is legendary, his discretion absolute.',
        personality: 'Friendly, practical, and fiercely neutral. A survivor who knows when to look the other way.',
        faction: 'NEUTRAL',
        dialogue: [
          'Welcome to Buckley\'s! If we don\'t have it, you probably don\'t need it.',
          'I sell to outlaws, lawmen, and everyone between. Gold is green no matter whose hand holds it.',
          'Some things I see, some things I don\'t. Depends on what\'s good for business.',
          'You look like you might need special accommodations. Sarah handles those arrangements.',
          'Been in Whiskey Bend fifteen years. Trick is staying useful and staying quiet.',
        ],
        isVendor: true,
        shopId: 'general-store-shop',
      },
      {
        id: 'sarah-buckley',
        name: 'Sarah Buckley',
        title: 'Business Manager',
        description: 'Hiram\'s wife and the real brains of the operation. Sharp as a razor and twice as dangerous, she handles the store\'s finances and its secret operations. Her calm demeanor masks a steel will and excellent aim with the shotgun under the counter.',
        personality: 'Shrewd, no-nonsense, and ruthlessly practical. Protects her family and business above all.',
        faction: 'NEUTRAL',
        dialogue: [
          'Hiram handles the smiles. I handle the numbers. Both keep us alive.',
          'You need something special? It\'ll cost extra. Discretion doesn\'t come cheap.',
          'I\'ve hidden outlaws, lawmen, and worse. Your money\'s the same color as theirs.',
          'Touch anything you haven\'t paid for and you\'ll meet my friend under the counter.',
        ],
      },
      {
        id: 'billy-buckley',
        name: 'Billy Buckley',
        title: 'Delivery Boy',
        description: 'The Buckleys\' teenage son, quick on his feet and wise beyond his years. He delivers goods throughout town and carries messages between factions. Nobody suspects a delivery boy.',
        personality: 'Clever, observant, and learning the family business. Eager to prove himself.',
        dialogue: [
          'Package for you, mister. Ma says no charge if you got news for her.',
          'I seen lots delivering packages. Folks don\'t notice the delivery boy.',
          'Pa says neutral is the only safe side in Whiskey Bend. I\'m learning.',
        ],
      },
    ],
    availableActions: ['buy-supplies', 'sell-goods', 'special-order', 'gather-information', 'send-message'],
    availableCrimes: ['Shoplift', 'Rob Store', 'Steal Shipment'],
    jobs: [
      {
        id: 'stock-shelves',
        name: 'Stock Shelves',
        description: 'Organize inventory and help customers find goods.',
        energyCost: 8,
        cooldownMinutes: 20,
        rewards: { goldMin: 8, goldMax: 15, xp: 12, items: [] },
        requirements: { minLevel: 1 },
      },
      {
        id: 'delivery-boy',
        name: 'Delivery Service',
        description: 'Deliver goods throughout Whiskey Bend. Sometimes carry messages.',
        energyCost: 12,
        cooldownMinutes: 30,
        rewards: { goldMin: 18, goldMax: 30, xp: 25, items: [] },
        requirements: { minLevel: 3 },
      },
      {
        id: 'inventory-manager',
        name: 'Inventory Management',
        description: 'Manage stock, track shipments, and handle special orders.',
        energyCost: 15,
        cooldownMinutes: 45,
        rewards: { goldMin: 30, goldMax: 55, xp: 45, items: [] },
        requirements: { minLevel: 8 },
      },
    ],
    shops: [
      {
        id: 'general-store-shop',
        name: 'Frontier General Store',
        description: 'General goods, provisions, tools, and ammunition.',
        shopType: 'general',
        items: [
          { itemId: 'flour-sack', name: 'Flour (50lb)', description: 'Essential provisions', price: 3 },
          { itemId: 'coffee-beans', name: 'Coffee (1lb)', description: 'Frontier fuel', price: 2 },
          { itemId: 'ammunition-box', name: 'Ammunition Box', description: '.45 caliber rounds', price: 15 },
          { itemId: 'rope-coil', name: 'Hemp Rope (50ft)', description: 'Multipurpose', price: 5 },
          { itemId: 'lantern-oil', name: 'Lantern Oil', description: 'For lamps and lanterns', price: 4 },
          { itemId: 'work-gloves', name: 'Work Gloves', description: 'Leather work gloves', price: 6 },
          { itemId: 'pickaxe', name: 'Pickaxe', description: 'Mining or digging', price: 25 },
          { itemId: 'bedroll', name: 'Bedroll', description: 'Sleep anywhere', price: 12 },
          { itemId: 'canteen', name: 'Canteen', description: 'Water storage', price: 8 },
          { itemId: 'tobacco-pouch', name: 'Tobacco Pouch', description: 'Quality pipe tobacco', price: 5 },
        ],
        buyMultiplier: 0.6,
      },
    ],
    secrets: [
      {
        id: 'safe-room',
        name: 'The Safe Room',
        description: 'A hidden room beneath the store accessed through a trapdoor behind the counter. The Buckleys hide people here for substantial fees - wanted outlaws, fleeing witnesses, cheating spouses, anyone with gold and a need to disappear. They ask no questions and tell no tales.',
        type: 'hidden_room',
        unlockCondition: {
          minReputation: 50,
          npcTrust: { npcId: 'sarah-buckley', level: 3 },
        },
        content: {
          actions: ['hide-out', 'arrange-escape', 'store-contraband', 'meet-contact'],
          npcs: ['sarah-buckley'],
          dialogue: [
            'We\'ve hidden everyone from senators to serial killers. Your money is good, your secrets are safe. Don\'t make us regret this.',
          ],
        },
      },
    ],
    connections: [],
    dangerLevel: 3,
    factionInfluence: { settlerAlliance: 40, nahiCoalition: 30, frontera: 30 },
    isUnlocked: true,
    isHidden: false,
  },

  // ===== 11. GOLDEN HORSESHOE THEATRE =====
  {
    _id: WHISKEY_BEND_BUILDING_IDS.GOLDEN_HORSESHOE_THEATRE,
    name: 'Golden Horseshoe Theatre',
    description: 'The grandest entertainment venue in Whiskey Bend, where Victoria DeVere presides over shows, secrets, and sins. The ornate theatre serves triple duty - public performances on stage, private high-stakes gambling in back rooms, and the most sophisticated espionage network in the territory.',
    shortDescription: 'Theatre, gambling den, and spy hub',
    type: 'theatre',
    region: 'town',
    parentId: LOCATION_IDS.WHISKEY_BEND,
    tier: 4,
    dominantFaction: 'neutral',
    operatingHours: { open: 18, close: 4 },
    atmosphere: 'Red velvet curtains frame a gilt-edged stage. Crystal chandeliers cast rainbow light across ornate balconies. Gaslight glamour meets frontier grit as cultured audiences watch performances while private rooms host card games with five-figure buy-ins. Behind painted smiles, performers catalogue secrets whispered in darkened boxes. Beauty, danger, and intrigue dance together.',
    requirements: { minLevel: 2 },
    npcs: [
      {
        id: 'victoria-devere',
        name: 'Victoria DeVere',
        title: 'Theatre Owner & Actress',
        description: 'A stunning actress of mysterious origins who transformed the Golden Horseshoe into Whiskey Bend\'s cultural center and intelligence hub. She performs tragic heroines on stage while running espionage operations backstage. Her beauty is legendary, her network formidable, her knowledge absolute.',
        personality: 'Sophisticated, manipulative, and brilliant. Values information above all else. Charm conceals calculation.',
        faction: 'NEUTRAL',
        dialogue: [
          'All the world\'s a stage, darling. I simply control the curtains and collect the reviews.',
          'Information is theatre\'s greatest art. Everyone performs, everyone reveals, everyone pays.',
          'My performers are artists of extraction. They sing, dance, and gather secrets you wouldn\'t tell God.',
          'The show tonight? Merely the opening act. The real drama unfolds in private boxes.',
          'I know everyone in Whiskey Bend. Their secrets, their desires, their weaknesses. That makes me invaluable.',
        ],
        isVendor: false,
        quests: ['extract-confession', 'infiltrate-meeting', 'expose-conspiracy'],
      },
      {
        id: 'magnificent-marcel',
        name: 'The Magnificent Marcel',
        title: 'Stage Magician',
        description: 'A charming Frenchman who performs illusions and sleight of hand on stage while running confidence games off it. He can make things disappear - cards, jewelry, evidence, people. No one knows if Marcel is even his real name.',
        personality: 'Charismatic, deceptive, and dangerously clever. Everything is misdirection.',
        faction: 'NEUTRAL',
        dialogue: [
          'Watch closely, mes amis! The hand is quicker than the eye, and the truth is always hidden.',
          'Magic is simply convincing people to see what you want them to see. A useful skill in many trades.',
          'That watch was in your pocket? How fascinating! It appears to have relocated. For a fee, it can relocate back.',
          'I once made a man\'s entire fortune disappear. He watched the whole time and never saw how.',
        ],
      },
      {
        id: 'dancing-delilah',
        name: 'Dancing Delilah',
        title: 'Lead Dancer',
        description: 'A beautiful dancer with a photographic memory. She performs for audiences while memorizing every conversation in the theatre. Victoria\'s most valuable operative.',
        personality: 'Graceful, observant, and loyal to Victoria. Perfectly plays the carefree performer.',
        dialogue: [
          'The view from the stage is magnificent. I can see and hear everything.',
          'Men talk freely when they think I\'m just a pretty dancer. I remember every word.',
          'Victoria taught me that the best intelligence comes from those who don\'t know they\'re revealing it.',
        ],
      },
      {
        id: 'singing-sally',
        name: 'Singing Sally',
        title: 'Soprano',
        description: 'A talented singer with a voice like an angel and ears like a bat. She performs in private boxes, gathering secrets from wealthy patrons.',
        personality: 'Sweet exterior hiding sharp intelligence. Masters the art of seeming harmless.',
        dialogue: [
          'They request private performances. I sing beautifully while listening carefully.',
          'People confess the strangest things to someone they consider beneath their notice.',
          'My voice opens doors. What I hear behind them pays better than applause.',
        ],
      },
      {
        id: 'piano-pete',
        name: '"Piano" Pete Morrison',
        title: 'Pianist',
        description: 'The theatre\'s musical director and Victoria\'s information coordinator. He seems to just play piano, but he processes and files every secret gathered by the performers.',
        personality: 'Quiet, organized, and essential. The memory bank of Victoria\'s network.',
        dialogue: [
          'I play the piano. I also play the information game. Both require perfect timing.',
          'Every performer reports to me. I catalogue, cross-reference, and file everything.',
          'Music and secrets both have patterns. I\'m good at recognizing both.',
        ],
      },
    ],
    availableActions: ['watch-performance', 'private-gambling', 'buy-information', 'hire-performer-spy', 'arrange-meeting'],
    availableCrimes: ['Cheat at Cards', 'Plant Spy', 'Blackmail Target'],
    jobs: [
      {
        id: 'stagehand',
        name: 'Stagehand Work',
        description: 'Move scenery, manage lighting, help with performances. See everything backstage.',
        energyCost: 10,
        cooldownMinutes: 25,
        rewards: { goldMin: 12, goldMax: 22, xp: 18, items: [] },
        requirements: { minLevel: 1 },
      },
      {
        id: 'performer',
        name: 'Performer',
        description: 'Act, sing, or dance on stage while gathering information from the audience.',
        energyCost: 18,
        cooldownMinutes: 45,
        rewards: { goldMin: 30, goldMax: 55, xp: 40, items: [] },
        requirements: { minLevel: 5 },
      },
      {
        id: 'talent-scout',
        name: 'Talent Scout',
        description: 'Recruit new performers and identify potential intelligence assets.',
        energyCost: 20,
        cooldownMinutes: 55,
        rewards: { goldMin: 40, goldMax: 70, xp: 55, items: [] },
        requirements: { minLevel: 10 },
      },
    ],
    shops: [
      {
        id: 'theatre-shop',
        name: 'Theatre Box Office',
        description: 'Tickets, refreshments, and special arrangements.',
        shopType: 'entertainment',
        items: [
          { itemId: 'theatre-ticket', name: 'Performance Ticket', description: 'Enjoy the show, restore energy', price: 10 },
          { itemId: 'private-box', name: 'Private Box Rental', description: 'Discrete viewing and meetings', price: 50 },
          { itemId: 'champagne-bottle', name: 'Champagne Bottle', description: 'Finest French import', price: 30 },
          { itemId: 'gambling-entry', name: 'High Stakes Room Access', description: '$500 minimum buy-in', price: 500, requiredLevel: 8 },
          { itemId: 'information-package', name: 'Intelligence Package', description: 'Secrets for sale', price: 200, requiredLevel: 10 },
        ],
        buyMultiplier: 0.3,
      },
    ],
    secrets: [
      {
        id: 'intelligence-archive',
        name: 'The Archive',
        description: 'Victoria\'s secret office containing comprehensive files on every significant person in the territory. Performer reports, intercepted correspondence, photographs, and recordings create the most complete intelligence database in the West. Access means power.',
        type: 'hidden_room',
        unlockCondition: {
          minReputation: 80,
          npcTrust: { npcId: 'victoria-devere', level: 5 },
        },
        content: {
          actions: ['study-intelligence', 'plan-operation', 'recruit-spy', 'sell-information'],
          npcs: ['piano-pete'],
          dialogue: [
            'Welcome to the Archive, darling. Here lies the truth behind every facade in this territory. Use it wisely - knowledge is the deadliest weapon.',
          ],
        },
      },
    ],
    connections: [],
    dangerLevel: 5,
    factionInfluence: { settlerAlliance: 35, nahiCoalition: 25, frontera: 40 },
    isUnlocked: true,
    isHidden: false,
  },

  // ===== 12. COFFIN MAKER'S SHOP =====
  {
    _id: WHISKEY_BEND_BUILDING_IDS.COFFIN_MAKER_SHOP,
    name: "Coffin Maker's Shop",
    description: 'Silas Grimm builds coffins for the dead and new lives for the desperate. His somber shop handles Whiskey Bend\'s frequent funerals, but his real business is faking deaths - staged murders, false graves, new identities, and safe passage out of the territory for those who can pay.',
    shortDescription: 'Undertaker and identity specialist',
    type: 'undertaker',
    region: 'town',
    parentId: LOCATION_IDS.WHISKEY_BEND,
    tier: 4,
    dominantFaction: 'neutral',
    operatingHours: { open: 0, close: 23 }, // 24/7 - death waits for no one
    atmosphere: 'The smell of sawdust, formaldehyde, and beeswax pervades the workshop. Half-finished coffins line the walls like silent witnesses. Grimm works with quiet efficiency, measuring, sawing, and sanding. The back room\'s locked door leads to his real work - the tools of transformation and rebirth through carefully staged death.',
    npcs: [
      {
        id: 'silas-grimm',
        name: 'Silas Grimm',
        title: 'Undertaker & Fixer',
        description: 'A tall, gaunt man with gentle hands and calculating eyes. He\'s buried half of Whiskey Bend and given new life to dozens more through his false death service. Practical and discreet, he views death as just another transaction - one he\'s learned to manipulate masterfully.',
        personality: 'Calm, pragmatic, and eerily comfortable around death. Respects those who understand mortality\'s value.',
        faction: 'NEUTRAL',
        dialogue: [
          'Death comes to everyone eventually. Sometimes I just... negotiate the timing.',
          'A proper funeral costs fifty dollars. A false funeral costs five thousand. Both are convincing.',
          'I\'ve buried empty coffins and living men. In Whiskey Bend, both services are equally valuable.',
          'You want to die? I can arrange that. You\'ll wake up three states away with a new name and a fresh start.',
          'The secret to faking death is simple - everyone must believe it. I\'m very convincing.',
        ],
        isVendor: true,
        shopId: 'coffin-shop',
        quests: ['stage-false-death', 'dispose-evidence', 'create-new-identity'],
      },
      {
        id: 'jacob-grimm',
        name: 'Jacob Grimm',
        title: 'Apprentice',
        description: 'Silas\'s younger brother and apprentice, learning both the undertaking trade and the false death business. Quieter and more nervous than his brother, but equally skilled with tools and discretion.',
        personality: 'Quiet, nervous, but reliable. Learning the family business with dedication.',
        dialogue: [
          'Uncle Silas says death is just carpentry with consequences. I\'m learning both.',
          'I\'ve helped stage twelve deaths this year. All of them are alive somewhere, far away.',
          'The graves in the back? Some are real, some aren\'t. I\'ll never tell which.',
        ],
      },
      {
        id: 'mourning-martha',
        name: 'Mourning Martha',
        title: 'Professional Mourner',
        description: 'An old woman who cries at funerals for a fee. She\'s attended hundreds of burials, making false funerals completely convincing. Her tears are fake but her discretion is real.',
        personality: 'Theatrical, professional, and utterly reliable. Takes her performance seriously.',
        dialogue: [
          'I\'ve cried at more funerals than anyone alive. Some were even real.',
          'They pay me to wail and weep. I\'m very good at both.',
          'I never ask if the coffin\'s full. I just cry convincingly and collect my fee.',
        ],
      },
    ],
    availableActions: ['order-coffin', 'arrange-funeral', 'fake-death', 'new-identity', 'dispose-body'],
    availableCrimes: ['Grave Robbing', 'Forge Death Certificate', 'Body Disposal'],
    jobs: [
      {
        id: 'grave-digger',
        name: 'Grave Digging',
        description: 'Dig graves in the cemetery. Some stay empty, some don\'t.',
        energyCost: 12,
        cooldownMinutes: 30,
        rewards: { goldMin: 15, goldMax: 25, xp: 20, items: [] },
        requirements: { minLevel: 1 },
      },
      {
        id: 'body-preparation',
        name: 'Body Preparation',
        description: 'Prepare bodies for burial. Embalming and cosmetic work.',
        energyCost: 18,
        cooldownMinutes: 45,
        rewards: { goldMin: 30, goldMax: 50, xp: 35, items: [] },
        requirements: { minLevel: 5 },
      },
      {
        id: 'special-arrangements',
        name: 'Special Arrangements',
        description: 'Handle false deaths, identity changes, and discrete disappearances.',
        energyCost: 25,
        cooldownMinutes: 60,
        rewards: { goldMin: 60, goldMax: 120, xp: 70, items: [] },
        requirements: { minLevel: 12 },
      },
    ],
    shops: [
      {
        id: 'coffin-shop',
        name: "Grimm's Undertaking Services",
        description: 'Funeral services, coffins, and special arrangements.',
        shopType: 'services',
        items: [
          { itemId: 'pine-coffin', name: 'Pine Coffin', description: 'Basic burial', price: 25 },
          { itemId: 'oak-coffin', name: 'Oak Coffin', description: 'Quality craftsmanship', price: 75 },
          { itemId: 'mahogany-coffin', name: 'Mahogany Coffin', description: 'Finest materials', price: 150 },
          { itemId: 'funeral-service', name: 'Funeral Service', description: 'Complete burial arrangements', price: 50 },
          { itemId: 'embalming', name: 'Embalming Service', description: 'Preservation', price: 40 },
          { itemId: 'false-death-package', name: 'False Death Package', description: 'Complete staged death and new identity', price: 5000, requiredLevel: 15 },
          { itemId: 'new-identity', name: 'New Identity Papers', description: 'Complete documentation set', price: 1500, requiredLevel: 12 },
          { itemId: 'body-disposal', name: 'Discrete Disposal', description: 'No questions asked', price: 500, requiredLevel: 10 },
        ],
        buyMultiplier: 0.4,
      },
    ],
    secrets: [
      {
        id: 'false-graves',
        name: 'The False Graves',
        description: 'A section of the cemetery where Grimm buries empty coffins for clients who\'ve faked their deaths. Underground tunnels connect to a safe house where the "deceased" wait for their new identity papers and safe transport out of territory. Maps show where everyone who\'s "died" actually went.',
        type: 'hidden_room',
        unlockCondition: {
          minReputation: 65,
          npcTrust: { npcId: 'silas-grimm', level: 4 },
        },
        content: {
          actions: ['access-safe-house', 'study-records', 'arrange-disappearance', 'contact-departed'],
          npcs: ['jacob-grimm'],
          dialogue: [
            'These graves are empty, but the lives they ended were full. Everyone buried here walks somewhere else under a different name. Your secret\'s safe with the dead.',
          ],
        },
      },
    ],
    connections: [],
    dangerLevel: 4,
    factionInfluence: { settlerAlliance: 30, nahiCoalition: 35, frontera: 35 },
    isUnlocked: true,
    isHidden: false,
  },
];

/**
 * Seed Whiskey Bend buildings into the database
 */
export async function seedWhiskeyBendBuildings(): Promise<void> {
  try {
    // Verify Whiskey Bend exists
    const whiskeyBend = await Location.findById(LOCATION_IDS.WHISKEY_BEND);
    if (!whiskeyBend) {
      console.warn('Warning: Whiskey Bend location not found. Buildings will reference non-existent parent.');
    }

    // Delete existing Whiskey Bend buildings (by parentId)
    await Location.deleteMany({ parentId: LOCATION_IDS.WHISKEY_BEND });

    // Insert Whiskey Bend buildings
    await Location.insertMany(whiskeyBendBuildings);

    console.log(`Successfully seeded ${whiskeyBendBuildings.length} Whiskey Bend buildings`);
  } catch (error) {
    console.error('Error seeding Whiskey Bend buildings:', error);
    throw error;
  }
}

export default whiskeyBendBuildings;
