/**
 * Kaiowa Mesa Buildings Seed Data
 *
 * Seeds the database with 8 buildings for Kaiowa Mesa,
 * a Tier 5 Nahi Coalition stronghold on an 800-foot mesa
 */

import mongoose from 'mongoose';
import logger from '../utils/logger';
import { Location } from '../models/Location.model';
import { LOCATION_IDS } from './locations.seed';

// Building IDs for Kaiowa Mesa
export const KAIOWA_MESA_BUILDING_IDS = {
  GATHERING_LODGE: new mongoose.Types.ObjectId('6502c0000000000000000001'),
  PEACEKEEPER_LODGE: new mongoose.Types.ObjectId('6502c0000000000000000002'),
  MESA_TRADING_POST: new mongoose.Types.ObjectId('6502c0000000000000000003'),
  TRIBAL_TREASURY: new mongoose.Types.ObjectId('6502c0000000000000000004'),
  SPIRIT_LODGE: new mongoose.Types.ObjectId('6502c0000000000000000005'),
  COUNCIL_FIRE: new mongoose.Types.ObjectId('6502c0000000000000000006'),
  MEDICINE_LODGE: new mongoose.Types.ObjectId('6502c0000000000000000007'),
  WARRIORS_REST: new mongoose.Types.ObjectId('6502c0000000000000000008'),
  // Phase 1, Wave 1.2 - New Buildings
  COUNCIL_LODGE: new mongoose.Types.ObjectId('6502c0000000000000000009'),
  WARRIOR_SOCIETY_HALL: new mongoose.Types.ObjectId('6502c000000000000000000a'),
  BARTER_TRADING_POST: new mongoose.Types.ObjectId('6502c000000000000000000b'),
};

const kaiowaMesaBuildings = [
  // ===== 1. GATHERING LODGE =====
  {
    _id: KAIOWA_MESA_BUILDING_IDS.GATHERING_LODGE,
    name: 'Gathering Lodge',
    description: 'The heart of Kaiowa Mesa where the people come together. Stories are shared around the central fire, trade agreements are negotiated, and the bonds of community are strengthened through shared meals and conversation.',
    shortDescription: 'Community gathering place for stories and trade',
    type: 'trading_post',
    region: 'town',
    parentId: LOCATION_IDS.KAIOWA_MESA,
    tier: 5,
    dominantFaction: 'nahi',
    operatingHours: { open: 0, close: 23 }, // 24/7
    atmosphere: 'Warm firelight dances on the walls adorned with tribal symbols. The smell of cedar smoke and cooking stew fills the air. Elders share stories while traders negotiate quietly in the corners.',
    npcs: [
      {
        id: 'many-horses',
        name: 'Many Horses',
        title: 'Lodge Keeper',
        description: 'A broad-shouldered man with kind eyes and a welcoming smile. He ensures all who enter the lodge are fed and heard.',
        personality: 'Generous and diplomatic. Values harmony and fair dealing. Remembers everyone who passes through.',
        faction: 'NAHI_COALITION',
        dialogue: [
          'Welcome, friend. The fire is warm and the stew is hot.',
          'All are welcome at the Gathering Lodge. Share your stories with us.',
          'Trade should benefit both parties. Let us find common ground.',
        ],
      },
      {
        id: 'laughing-crow',
        name: 'Laughing Crow',
        title: 'Storyteller',
        description: 'An elderly woman with silver-streaked hair and eyes that sparkle with ancient wisdom. Her stories carry the history of the Nahi people.',
        personality: 'Playful yet wise. Uses humor to teach lessons. Keeper of oral traditions.',
        dialogue: [
          'Sit, young one. Let me tell you of the Old Times...',
          'Every story holds truth, if you know how to listen.',
          'Ha! That reminds me of when Coyote tried to steal the stars...',
        ],
      },
    ],
    availableActions: ['gather-rumors', 'trade', 'listen-story', 'share-meal'],
    availableCrimes: ['Pickpocket'],
    jobs: [
      {
        id: 'lodge-helper',
        name: 'Lodge Helper',
        description: 'Assist with serving meals and maintaining the lodge.',
        energyCost: 10,
        cooldownMinutes: 20,
        rewards: { goldMin: 10, goldMax: 18, xp: 20, items: [] },
        requirements: { minLevel: 1 },
      },
    ],
    shops: [
      {
        id: 'gathering-lodge-goods',
        name: 'Lodge Provisions',
        description: 'Simple foods and tobacco.',
        shopType: 'general',
        items: [
          { itemId: 'pemmican', name: 'Pemmican', description: 'Nourishing travel food', price: 4 },
          { itemId: 'herbal-tea', name: 'Herbal Tea', description: 'Calming blend', price: 2 },
          { itemId: 'sacred-tobacco', name: 'Sacred Tobacco', description: 'For ceremonies', price: 8 },
        ],
        buyMultiplier: 0.4,
      },
    ],
    secrets: [],
    connections: [],
    dangerLevel: 1,
    factionInfluence: { settlerAlliance: 5, nahiCoalition: 90, frontera: 5 },
    isUnlocked: true,
    isHidden: false,
  },

  // ===== 2. PEACEKEEPER LODGE =====
  {
    _id: KAIOWA_MESA_BUILDING_IDS.PEACEKEEPER_LODGE,
    name: 'Peacekeeper Lodge',
    description: 'The seat of tribal law enforcement on Kaiowa Mesa. The Peacekeepers maintain order according to ancient traditions, balancing justice with mercy.',
    shortDescription: 'Tribal law enforcement headquarters',
    type: 'sheriff_office',
    region: 'town',
    parentId: LOCATION_IDS.KAIOWA_MESA,
    tier: 5,
    dominantFaction: 'nahi',
    operatingHours: { open: 0, close: 23 }, // 24/7
    atmosphere: 'Weapons and shields of honored warriors line the walls. A war drum sits in the corner. Maps of Coalition territory cover a large table where strategies are planned.',
    requirements: { maxWanted: 30 },
    npcs: [
      {
        id: 'stone-bear',
        name: 'Stone Bear',
        title: 'Peacekeeper Chief',
        description: 'A massive man with a scarred face and the bearing of one who has seen many battles. His judgments are final and fair.',
        personality: 'Stoic and just. Weighs every decision carefully. Protects the weak, punishes the dishonorable.',
        faction: 'NAHI_COALITION',
        dialogue: [
          'Justice is not revenge. Remember this.',
          'A warrior\'s strength is measured by those he protects, not those he defeats.',
          'You bring trouble to our mesa? Then you answer to the Peacekeepers.',
        ],
        quests: ['track-dishonorable', 'defend-mesa'],
      },
      {
        id: 'swift-arrow',
        name: 'Swift Arrow',
        title: 'Warrior',
        description: 'A young warrior with quick reflexes and unwavering loyalty to the Peacekeeper Chief. He patrols the mesa paths day and night.',
        personality: 'Eager and vigilant. Seeks to prove himself worthy of his position.',
        faction: 'NAHI_COALITION',
        dialogue: [
          'The mesa is safe under our watch.',
          'I train every day. A warrior must always be ready.',
          'Stone Bear is teaching me to lead. It is a great honor.',
        ],
      },
    ],
    availableActions: ['check-bounties', 'report-dishonor', 'seek-justice', 'pay-restitution'],
    availableCrimes: [],
    jobs: [
      {
        id: 'mesa-patrol',
        name: 'Mesa Patrol',
        description: 'Guard the paths and watch for threats to the community.',
        energyCost: 15,
        cooldownMinutes: 30,
        rewards: { goldMin: 18, goldMax: 30, xp: 30, items: [] },
        requirements: { minLevel: 3 },
      },
      {
        id: 'honor-hunt',
        name: 'Honor Hunt',
        description: 'Track down those who have broken tribal law.',
        energyCost: 25,
        cooldownMinutes: 60,
        rewards: { goldMin: 40, goldMax: 70, xp: 60, items: [] },
        requirements: { minLevel: 8 },
      },
    ],
    shops: [],
    connections: [],
    dangerLevel: 3,
    factionInfluence: { settlerAlliance: 0, nahiCoalition: 98, frontera: 2 },
    isUnlocked: true,
    isHidden: false,
  },

  // ===== 3. MESA TRADING POST =====
  {
    _id: KAIOWA_MESA_BUILDING_IDS.MESA_TRADING_POST,
    name: 'Mesa Trading Post',
    description: 'A well-stocked trading post offering tribal goods, medicinal herbs, and fine Nahi crafts. Silver Moon ensures fair prices and quality goods for all.',
    shortDescription: 'Tribal goods, herbs, and crafts',
    type: 'general_store',
    region: 'town',
    parentId: LOCATION_IDS.KAIOWA_MESA,
    tier: 5,
    dominantFaction: 'nahi',
    operatingHours: { open: 6, close: 20 },
    atmosphere: 'Bundles of dried herbs hang from the rafters. Beaded jewelry and woven blankets are displayed with care. The scent of sage and sweetgrass perfumes the air.',
    npcs: [
      {
        id: 'silver-moon',
        name: 'Silver Moon',
        title: 'Trader',
        description: 'A sharp-eyed woman with intricate silver jewelry adorning her braids. She knows the value of every item and drives a fair bargain.',
        personality: 'Shrewd but honest. Takes pride in quality craftsmanship. Supports local artisans.',
        faction: 'NAHI_COALITION',
        dialogue: [
          'These blankets are woven by the finest hands on the mesa.',
          'I trade with all peoples, but I never cheat my own.',
          'The herbs? Gathered at dawn when their power is strongest.',
        ],
        isVendor: true,
        shopId: 'mesa-trading-shop',
      },
    ],
    availableActions: ['buy', 'sell', 'trade', 'commission-craft'],
    availableCrimes: ['Burglarize Store', 'Pickpocket'],
    jobs: [
      {
        id: 'trading-assistant',
        name: 'Trading Assistant',
        description: 'Help organize goods and assist customers.',
        energyCost: 10,
        cooldownMinutes: 20,
        rewards: { goldMin: 10, goldMax: 16, xp: 18, items: [] },
        requirements: { minLevel: 1 },
      },
    ],
    shops: [
      {
        id: 'mesa-trading-shop',
        name: 'Mesa Trading Post',
        description: 'Tribal goods and medicinal herbs.',
        shopType: 'general',
        items: [
          { itemId: 'healing-herbs', name: 'Healing Herbs', description: 'Traditional medicine', price: 15 },
          { itemId: 'beaded-amulet', name: 'Beaded Amulet', description: 'Protective charm', price: 30 },
          { itemId: 'woven-blanket', name: 'Woven Blanket', description: 'Keeps you warm', price: 20 },
          { itemId: 'sage-bundle', name: 'Sage Bundle', description: 'For purification', price: 8 },
          { itemId: 'flint-knife', name: 'Flint Knife', description: 'Traditional blade', price: 18 },
          { itemId: 'spirit-paint', name: 'Spirit Paint', description: 'War paint set', price: 25, requiredLevel: 5 },
        ],
        buyMultiplier: 0.5,
      },
    ],
    connections: [],
    dangerLevel: 1,
    factionInfluence: { settlerAlliance: 5, nahiCoalition: 90, frontera: 5 },
    isUnlocked: true,
    isHidden: false,
  },

  // ===== 4. TRIBAL TREASURY =====
  {
    _id: KAIOWA_MESA_BUILDING_IDS.TRIBAL_TREASURY,
    name: 'Tribal Treasury',
    description: 'The communal fund of Kaiowa Mesa, managed with wisdom and integrity. Resources are shared according to need, and Counting Eagle ensures every contribution is honored.',
    shortDescription: 'Communal banking and resource management',
    type: 'bank',
    region: 'town',
    parentId: LOCATION_IDS.KAIOWA_MESA,
    tier: 5,
    dominantFaction: 'nahi',
    operatingHours: { open: 8, close: 18 },
    atmosphere: 'Carefully arranged ledgers made of hide record every transaction. Carved tokens represent different values. The room speaks of orderly tradition.',
    npcs: [
      {
        id: 'counting-eagle',
        name: 'Counting Eagle',
        title: 'Treasurer',
        description: 'A meticulous elder with a phenomenal memory for numbers and names. He can recall every transaction made in the past thirty winters.',
        personality: 'Precise and patient. Believes wealth should flow to where it is needed. Incorruptible.',
        faction: 'NAHI_COALITION',
        dialogue: [
          'The wealth of the people belongs to all the people.',
          'Your contribution is recorded. The community thanks you.',
          'In times of plenty, we save. In times of need, we share.',
        ],
        isVendor: false,
      },
    ],
    availableActions: ['deposit', 'withdraw', 'check-balance', 'contribute-community', 'request-aid'],
    availableCrimes: ['Treasury Theft'],
    jobs: [],
    shops: [],
    connections: [],
    dangerLevel: 2,
    factionInfluence: { settlerAlliance: 0, nahiCoalition: 98, frontera: 2 },
    isUnlocked: true,
    isHidden: false,
  },

  // ===== 5. SPIRIT LODGE =====
  {
    _id: KAIOWA_MESA_BUILDING_IDS.SPIRIT_LODGE,
    name: 'Spirit Lodge',
    description: 'The sacred place where Wise Sky communes with the spirits. Those who seek visions, blessings, or guidance come here to connect with powers beyond the mortal world.',
    shortDescription: 'Mystical visions, buffs, and spiritual quests',
    type: 'spirit_lodge',
    region: 'town',
    parentId: LOCATION_IDS.KAIOWA_MESA,
    tier: 5,
    dominantFaction: 'nahi',
    operatingHours: { open: 0, close: 23 }, // 24/7
    atmosphere: 'Sacred smoke rises from the central fire pit. Dream catchers and spirit symbols adorn every surface. The air thrums with unseen power, and shadows move of their own accord.',
    npcs: [
      {
        id: 'wise-sky',
        name: 'Wise Sky',
        title: 'Elder Shaman',
        description: 'An ancient shaman whose eyes seem to look beyond the physical world. They speak in riddles that hold profound truth for those who can understand.',
        personality: 'Enigmatic and profound. Sees past, present, and future as one. Tests those who seek their wisdom.',
        faction: 'NAHI_COALITION',
        dialogue: [
          'The spirits speak to those who know how to listen...',
          'You seek power? First seek understanding.',
          'Your path is shrouded, but the spirits show me... possibilities.',
        ],
        quests: ['vision-quest', 'spirit-trial'],
      },
    ],
    availableActions: ['seek-vision', 'receive-blessing', 'commune-spirits', 'spirit-quest'],
    availableCrimes: [],
    jobs: [
      {
        id: 'spirit-apprentice',
        name: 'Spirit Apprentice',
        description: 'Assist in ceremonies and learn the old ways.',
        energyCost: 20,
        cooldownMinutes: 45,
        rewards: { goldMin: 15, goldMax: 25, xp: 40, items: [] },
        requirements: { minLevel: 5 },
      },
    ],
    shops: [
      {
        id: 'spirit-lodge-offerings',
        name: 'Spiritual Offerings',
        description: 'Sacred items and vision aids.',
        shopType: 'specialty',
        items: [
          { itemId: 'vision-herbs', name: 'Vision Herbs', description: 'Opens the mind\'s eye', price: 50 },
          { itemId: 'spirit-feather', name: 'Spirit Feather', description: 'Eagle blessing', price: 40 },
          { itemId: 'dream-catcher', name: 'Dream Catcher', description: 'Filters nightmares', price: 35 },
          { itemId: 'spirit-stone', name: 'Spirit Stone', description: 'Enhances connection', price: 75, requiredLevel: 10 },
        ],
        buyMultiplier: 0.3,
      },
    ],
    connections: [],
    dangerLevel: 2,
    factionInfluence: { settlerAlliance: 0, nahiCoalition: 100, frontera: 0 },
    isUnlocked: true,
    isHidden: false,
  },

  // ===== 6. COUNCIL FIRE =====
  {
    _id: KAIOWA_MESA_BUILDING_IDS.COUNCIL_FIRE,
    name: 'Council Fire',
    description: 'Where the leaders of the Nahi Coalition gather to debate strategy, forge alliances, and plan for war. Red Thunder presides over these meetings with fierce determination.',
    shortDescription: 'Faction politics and war planning',
    type: 'council_fire',
    region: 'town',
    parentId: LOCATION_IDS.KAIOWA_MESA,
    tier: 5,
    dominantFaction: 'nahi',
    operatingHours: { open: 18, close: 2 }, // Evening meetings
    atmosphere: 'A great fire burns at the center of the stone circle. War maps are spread on flat rocks. The faces of warriors are painted for council. Tension and determination fill the air.',
    requirements: { minLevel: 5 },
    npcs: [
      {
        id: 'red-thunder',
        name: 'Red Thunder',
        title: 'War Chief',
        description: 'A legendary warrior whose battle cry is said to shake the mountains. He leads the Coalition\'s military forces with tactical brilliance and unshakeable courage.',
        personality: 'Fierce and strategic. Values bravery and loyalty above all. Will sacrifice himself for his people.',
        faction: 'NAHI_COALITION',
        dialogue: [
          'The settlers push into our lands. We will push back.',
          'War is not glory. War is necessity. Remember this.',
          'You wish to fight for the Coalition? Then prove your worth.',
        ],
        quests: ['war-party', 'defend-territory', 'raid-enemy'],
      },
    ],
    availableActions: ['attend-council', 'volunteer-war-party', 'report-enemy-movement', 'request-alliance'],
    availableCrimes: [],
    jobs: [
      {
        id: 'war-scout',
        name: 'War Scout',
        description: 'Gather intelligence on enemy positions and movements.',
        energyCost: 30,
        cooldownMinutes: 60,
        rewards: { goldMin: 35, goldMax: 55, xp: 50, items: [] },
        requirements: { minLevel: 8 },
      },
    ],
    shops: [],
    secrets: [
      {
        id: 'war-council-inner',
        name: 'Inner War Council',
        description: 'The innermost circle where the most sensitive strategies are discussed.',
        type: 'hidden_room',
        unlockCondition: {
          minReputation: 80,
          npcTrust: { npcId: 'red-thunder', level: 4 },
        },
        content: {
          actions: ['plan-major-offensive', 'access-war-chest'],
          npcs: ['shadow-warrior'],
          dialogue: ['You have earned our trust. Now hear our true plans...'],
        },
      },
    ],
    connections: [],
    dangerLevel: 4,
    factionInfluence: { settlerAlliance: 0, nahiCoalition: 100, frontera: 0 },
    isUnlocked: true,
    isHidden: false,
  },

  // ===== 7. MEDICINE LODGE =====
  {
    _id: KAIOWA_MESA_BUILDING_IDS.MEDICINE_LODGE,
    name: 'Medicine Lodge',
    description: 'Where the body and spirit are healed as one. Healing Hand combines ancient herbal knowledge with spiritual practices to cure ailments that baffle western doctors.',
    shortDescription: 'Spiritual and physical healing',
    type: 'medicine_lodge',
    region: 'town',
    parentId: LOCATION_IDS.KAIOWA_MESA,
    tier: 5,
    dominantFaction: 'nahi',
    operatingHours: { open: 0, close: 23 }, // 24/7
    atmosphere: 'Bundles of drying herbs cover every surface. A small fire heats healing stones. Soft chanting and the rattle of gourds create a soothing rhythm. Patients rest on soft furs.',
    npcs: [
      {
        id: 'healing-hand',
        name: 'Healing Hand',
        title: 'Medicine Woman',
        description: 'A gentle woman whose touch seems to draw out pain and sickness. She learned the healing arts from her grandmother, and her grandmother before her.',
        personality: 'Compassionate and patient. Treats all who suffer, regardless of faction. Believes healing is a sacred duty.',
        faction: 'NAHI_COALITION',
        dialogue: [
          'Show me where it hurts. The body speaks if we listen.',
          'Western medicine treats symptoms. We treat the whole person.',
          'Rest now. Let the herbs and spirits do their work.',
        ],
        isVendor: true,
        shopId: 'medicine-lodge-shop',
      },
    ],
    availableActions: ['heal', 'buy-medicine', 'purification-ritual', 'spirit-cleansing'],
    availableCrimes: [],
    jobs: [
      {
        id: 'herb-gatherer',
        name: 'Herb Gatherer',
        description: 'Collect medicinal plants from the mesa.',
        energyCost: 12,
        cooldownMinutes: 25,
        rewards: { goldMin: 12, goldMax: 20, xp: 22, items: [] },
        requirements: { minLevel: 2 },
      },
    ],
    shops: [
      {
        id: 'medicine-lodge-shop',
        name: 'Medicine Lodge Remedies',
        description: 'Traditional medicines and healing items.',
        shopType: 'medicine',
        items: [
          { itemId: 'healing-poultice', name: 'Healing Poultice', description: 'Speeds wound recovery', price: 12 },
          { itemId: 'fever-bark', name: 'Fever Bark', description: 'Reduces fever', price: 8 },
          { itemId: 'spirit-tea', name: 'Spirit Tea', description: 'Restores energy', price: 20 },
          { itemId: 'purification-smoke', name: 'Purification Smoke', description: 'Cleanses ailments', price: 35 },
          { itemId: 'life-root', name: 'Life Root', description: 'Powerful restoration', price: 80, requiredLevel: 10 },
        ],
        buyMultiplier: 0.4,
      },
    ],
    connections: [],
    dangerLevel: 1,
    factionInfluence: { settlerAlliance: 5, nahiCoalition: 92, frontera: 3 },
    isUnlocked: true,
    isHidden: false,
  },

  // ===== 8. WARRIOR'S REST =====
  {
    _id: KAIOWA_MESA_BUILDING_IDS.WARRIORS_REST,
    name: "Warrior's Rest",
    description: 'A peaceful lodge where warriors and travelers can rest and recover their strength. Gentle Rain ensures every guest is comfortable and well-cared for.',
    shortDescription: 'Rest and recovery lodging',
    type: 'hotel',
    region: 'town',
    parentId: LOCATION_IDS.KAIOWA_MESA,
    tier: 5,
    dominantFaction: 'nahi',
    operatingHours: { open: 0, close: 23 }, // 24/7
    atmosphere: 'Soft furs and woven mats provide comfortable sleeping areas. A gentle breeze flows through, carrying the scent of pine from the mesa. The sounds of nature replace the noise of civilization.',
    npcs: [
      {
        id: 'gentle-rain',
        name: 'Gentle Rain',
        title: 'Caretaker',
        description: 'A soft-spoken woman with a calming presence. She moves quietly and anticipates every need before it is spoken.',
        personality: 'Nurturing and attentive. Creates peace wherever she goes. Protective of those in her care.',
        faction: 'NAHI_COALITION',
        dialogue: [
          'Welcome, weary traveler. Rest your body and your spirit here.',
          'I will bring you food and water. Sleep, and wake refreshed.',
          'The mesa is safe. Let your guard down, if only for a night.',
        ],
      },
    ],
    availableActions: ['rest', 'rent-room', 'eat-meal', 'store-items', 'meditate'],
    availableCrimes: ['Pickpocket'],
    jobs: [
      {
        id: 'lodge-tender',
        name: 'Lodge Tender',
        description: 'Help maintain the lodge and assist guests.',
        energyCost: 10,
        cooldownMinutes: 20,
        rewards: { goldMin: 10, goldMax: 16, xp: 18, items: [] },
        requirements: { minLevel: 1 },
      },
    ],
    shops: [
      {
        id: 'warriors-rest-meals',
        name: 'Lodge Meals',
        description: 'Nourishing food for rest and recovery.',
        shopType: 'general',
        items: [
          { itemId: 'venison-stew', name: 'Venison Stew', description: 'Hearty and filling', price: 3 },
          { itemId: 'corn-cakes', name: 'Corn Cakes', description: 'Traditional bread', price: 2 },
          { itemId: 'berry-juice', name: 'Berry Juice', description: 'Refreshing drink', price: 1 },
          { itemId: 'travelers-bundle', name: "Traveler's Bundle", description: 'Food for the road', price: 5 },
        ],
        buyMultiplier: 0.3,
      },
    ],
    connections: [],
    dangerLevel: 1,
    factionInfluence: { settlerAlliance: 5, nahiCoalition: 90, frontera: 5 },
    isUnlocked: true,
    isHidden: false,
  },

  // ============================================================
  // 9. COUNCIL LODGE - Phase 1, Wave 1.2
  // ============================================================
  {
    _id: KAIOWA_MESA_BUILDING_IDS.COUNCIL_LODGE,
    name: 'Council Lodge',
    description: 'The sacred meeting place where tribal elders gather beneath painted hide walls to decide the fate of the Coalition. Ancient treaty scrolls hang alongside war shields, and the air is thick with pipe smoke and deliberation. Eagle Who Sees Far presides with quiet wisdom, while voices rise and fall in debate over trade agreements, territorial disputes, and the future of the Nahi people.',
    shortDescription: 'Tribal council and diplomatic center',
    type: 'council_fire',
    region: 'town',
    parentId: LOCATION_IDS.KAIOWA_MESA,
    tier: 5,
    dominantFaction: 'nahi',
    operatingHours: { open: 8, close: 22 },
    atmosphere: 'Painted hide walls depict the history of the Coalition. Treaty scrolls hang beside war shields. Pipe smoke drifts through shafts of sunlight as elders debate in measured tones.',
    requirements: { minLevel: 10 },
    npcs: [
      {
        id: 'eagle-who-sees-far',
        name: 'Eagle Who Sees Far',
        title: 'Chief Elder',
        description: 'The eldest member of the Council, whose weathered face tells the story of seventy winters. His eyes miss nothing, and his words carry the weight of generations. He has guided the Coalition through wars, famines, and the encroachment of settlers, always seeking the path that preserves his people.',
        personality: 'Wise and patient, sees the long view of history. Balances tradition with pragmatism. Tests those who seek his counsel.',
        faction: 'NAHI_COALITION',
        dialogue: [
          'The Council speaks with one voice, but we listen to many. What wisdom do you bring?',
          'Our ancestors made treaties that their children broke. We remember. We do not forget.',
          'The settlers call this progress. We call it theft. Yet we must find a way to survive what we cannot prevent.',
          'Red Thunder speaks of war. I speak of strategy. Sometimes they are the same. Sometimes they are not.',
        ],
        quests: ['diplomatic_mission', 'treaty_negotiation', 'coalition_alliance'],
      },
      {
        id: 'white-buffalo-woman',
        name: 'White Buffalo Woman',
        title: 'Peace Speaker',
        description: 'A dignified woman whose silver-streaked braids reach her waist. She serves as the voice of the Council in negotiations with outsiders, speaking five languages fluently. Her diplomatic skills have prevented more bloodshed than most warriors could stop with weapons.',
        personality: 'Diplomatic and shrewd. Never shows anger but wields words like weapons. Deeply protective of Coalition interests.',
        faction: 'NAHI_COALITION',
        dialogue: [
          'I speak for the Council. My words are their words, chosen with care and spoken with purpose.',
          'The settlers respect strength. Show weakness, and they take everything. Show only strength, and they bring armies.',
          'Wise Sky sees the spirits. I see the patterns in how people behave. Both are prophecy.',
          'You wish to serve the Coalition? Then learn to listen more than you speak, and act more than you promise.',
        ],
        quests: ['ambassador_trial', 'peace_accord'],
      },
      {
        id: 'gray-wolf',
        name: 'Gray Wolf',
        title: 'War Councilor',
        description: 'A scarred veteran who sits at Red Thunder\'s right hand during council meetings. He has fought in more battles than he can count and carries the weight of lost warriors in his eyes. He argues for defense of Coalition lands with the passion of one who has buried friends.',
        personality: 'Fierce but not reckless. Values warrior honor but serves the Council\'s wisdom. Haunted by wars fought.',
        faction: 'NAHI_COALITION',
        dialogue: [
          'The Council deliberates. Warriors wait. And the enemy advances. This is the balance we must keep.',
          'I have seen what happens when we trust settlers. I have buried the result.',
          'Red Thunder is right - we must defend our lands. Eagle Who Sees Far is also right - we must survive. This is the warrior\'s dilemma.',
          'You want to join our war parties? First, join our Council meetings. Understand why we fight before you swing a blade.',
        ],
        quests: ['council_military_plan', 'defense_strategy'],
      },
      {
        id: 'morning-dove',
        name: 'Morning Dove',
        title: 'Record Keeper',
        description: 'A meticulous woman who maintains the Coalition\'s oral and written records. She remembers every treaty, every agreement, every promise made and broken. Her memory is considered sacred, and her word in disputes is final.',
        personality: 'Precise and neutral. Values truth and accuracy above all. Serves the historical record, not politics.',
        faction: 'NAHI_COALITION',
        dialogue: [
          'I remember what others forget. This is both my gift and my burden.',
          'They claim this land was never ours. I can recite twelve generations who say otherwise.',
          'Every decision the Council makes is recorded. Future generations will judge us by these words.',
          'You want to know what was decided fifty winters ago? Sit. I will tell you exactly what was said.',
        ],
        quests: ['historical_recovery', 'treaty_research'],
      },
      {
        id: 'black-elk',
        name: 'Black Elk',
        title: 'Trade Councilor',
        description: 'A pragmatic elder who manages the Coalition\'s trade relationships and barter economy. He understands that survival requires resources, and resources require careful negotiation. He works closely with Silver Moon at the Trading Post.',
        personality: 'Practical and business-minded. Values fair exchange and mutual benefit. Sees trade as diplomacy.',
        faction: 'NAHI_COALITION',
        dialogue: [
          'War costs resources. Peace creates them. This is simple truth the hotheads forget.',
          'We trade ceremonial tokens for what we need. Each token represents trust earned. This is our economy.',
          'The settlers have gold. We have goods, services, and honor. I know which has more value.',
          'Silver Moon handles daily trade. I handle the agreements that make trade possible.',
        ],
        quests: ['trade_route_security', 'barter_network'],
      },
    ],
    availableActions: ['attend-council', 'petition-elders', 'diplomatic-mission', 'review-treaties', 'coalition-business'],
    availableCrimes: ['Eavesdrop on Council', 'Steal Treaty Documents'],
    jobs: [
      {
        id: 'diplomatic_courier',
        name: 'Diplomatic Courier',
        description: 'Deliver sensitive messages between Coalition settlements. Discretion and speed required. White Buffalo Woman personally selects her couriers.',
        energyCost: 20,
        cooldownMinutes: 90,
        rewards: { goldMin: 40, goldMax: 65, xp: 80, items: ['diplomatic_seal', 'coalition_favor'] },
        requirements: { minLevel: 10 },
      },
      {
        id: 'peace_negotiation',
        name: 'Peace Negotiation',
        description: 'Assist White Buffalo Woman in delicate negotiations with rival factions. Your reputation and skill with words will be tested.',
        energyCost: 30,
        cooldownMinutes: 180,
        rewards: { goldMin: 80, goldMax: 130, xp: 150, items: ['negotiator_token', 'reputation_boost'] },
        requirements: { minLevel: 15 },
      },
      {
        id: 'council_research',
        name: 'Historical Research',
        description: 'Help Morning Dove research ancient treaties and agreements. Requires patience, attention to detail, and respect for tradition.',
        energyCost: 15,
        cooldownMinutes: 120,
        rewards: { goldMin: 35, goldMax: 55, xp: 90, items: ['historical_knowledge', 'ceremonial_token'] },
        requirements: { minLevel: 12 },
      },
      {
        id: 'trade_agreement',
        name: 'Trade Agreement Facilitation',
        description: 'Assist Black Elk in establishing new trade agreements. Travel to distant settlements, negotiate terms, and secure resources for the Coalition.',
        energyCost: 35,
        cooldownMinutes: 240,
        rewards: { goldMin: 100, goldMax: 160, xp: 180, items: ['trade_charter', 'exotic_goods', 'ceremonial_token'] },
        requirements: { minLevel: 18 },
      },
      {
        id: 'military_liaison',
        name: 'Council-Warrior Liaison',
        description: 'Serve as messenger between the Council and Red Thunder\'s warriors. Requires understanding of both diplomacy and military matters.',
        energyCost: 25,
        cooldownMinutes: 150,
        rewards: { goldMin: 60, goldMax: 95, xp: 120, items: ['liaison_badge', 'warrior_respect'] },
        requirements: { minLevel: 20 },
      },
      {
        id: 'coalition_mission',
        name: 'Coalition Strategic Mission',
        description: 'High-level mission assigned directly by Eagle Who Sees Far. Critical to Coalition interests. Details revealed only to trusted agents.',
        energyCost: 45,
        cooldownMinutes: 360,
        rewards: { goldMin: 150, goldMax: 240, xp: 280, items: ['chief_commendation', 'rare_artifact', 'sacred_item'] },
        requirements: { minLevel: 25 },
      },
    ],
    shops: [],
    secrets: [
      {
        id: 'ancient_treaties',
        name: 'Chamber of Ancient Treaties',
        description: 'A hidden chamber beneath the Council Lodge where the oldest and most sacred treaties are preserved. Documents dating back centuries, including agreements with tribes long scattered and promises made by governments long fallen. The knowledge here could shift the balance of power in the entire territory.',
        type: 'hidden_room',
        unlockCondition: {
          minReputation: 80,
          npcTrust: { npcId: 'eagle-who-sees-far', level: 4 },
        },
        content: {
          actions: ['study_ancient_treaties', 'copy_historical_records', 'uncover_hidden_alliances'],
          npcs: [],
          dialogue: [
            '"You have earned the Council\'s trust. What I show you now has been hidden for generations. Treaties signed in blood and broken in greed. Alliances that still hold power if we know how to invoke them. Use this knowledge to protect our people."',
          ],
        },
      },
      {
        id: 'hidden_alliance',
        name: 'Secret Alliance Network',
        description: 'White Buffalo Woman maintains a covert network of sympathizers within settler and Frontera territories - traders, scouts, and displaced Nahi who feed intelligence back to the Council. This network is the Coalition\'s eyes and ears across the territory.',
        type: 'progressive',
        unlockCondition: {
          minReputation: 70,
          npcTrust: { npcId: 'white-buffalo-woman', level: 5 },
        },
        content: {
          actions: ['access_intelligence_network', 'recruit_informant', 'coordinate_covert_ops'],
          npcs: [],
          dialogue: [
            '"The Council knows more than we reveal. We have friends in unexpected places - settlers who respect our ways, Frontera who remember we aided their revolution, traders who value partnership over profit. I am trusting you with our most valuable asset: information. Betray this trust, and you betray all the Nahi people."',
          ],
        },
      },
    ],
    connections: [],
    dangerLevel: 2,
    factionInfluence: { settlerAlliance: 5, nahiCoalition: 95, frontera: 10 },
    isUnlocked: true,
    isHidden: false,
  },

  // ============================================================
  // 10. WARRIOR SOCIETY HALL - Phase 1, Wave 1.2
  // ============================================================
  {
    _id: KAIOWA_MESA_BUILDING_IDS.WARRIOR_SOCIETY_HALL,
    name: 'Warrior Society Hall',
    description: 'A fortified lodge where the Coalition\'s finest warriors train, plan raids, and honor their fallen brothers and sisters. The walls are adorned with captured weapons, war shields bearing proud histories, and the names of legendary fighters carved in stone. The sound of sparring, the ring of steel on steel, and the rhythmic chants of war songs fill the air. This is where warriors are forged and legends are born.',
    shortDescription: 'Elite warrior training and war planning',
    type: 'outpost',
    region: 'town',
    parentId: LOCATION_IDS.KAIOWA_MESA,
    tier: 5,
    dominantFaction: 'nahi',
    operatingHours: { open: 5, close: 23 },
    atmosphere: 'War shields and captured weapons line the walls. The training ground echoes with the clash of blades and war cries. Smoke from the sacred fire carries prayers to the warrior spirits.',
    requirements: { minLevel: 8 },
    npcs: [
      {
        id: 'iron-fist',
        name: 'Iron Fist',
        title: 'Master of Arms',
        description: 'A legendary warrior whose scarred knuckles have broken more bones than most people have in their bodies. He trains Coalition warriors in hand-to-hand combat, teaching techniques passed down through generations. His methods are brutal, but those who survive his training become formidable fighters.',
        personality: 'Harsh but fair. Respects strength and determination. Believes pain is the best teacher. Fiercely loyal to Red Thunder.',
        faction: 'NAHI_COALITION',
        dialogue: [
          'Pain is temporary. Weakness is forever. Which do you choose?',
          'The settlers have guns. We have skill, speed, and the blessing of the warrior spirits. I know which advantage I prefer.',
          'You want to join Red Thunder\'s war parties? First, survive my training. Many try. Few succeed.',
          'Iron Fist is not my birth name. It is what I became. What will you become?',
        ],
        quests: ['warrior_trial', 'combat_mastery'],
      },
      {
        id: 'she-wolf',
        name: 'She-Wolf',
        title: 'Raid Commander',
        description: 'A fierce warrior woman who leads the Coalition\'s most daring raids. She moves like smoke, strikes like lightning, and shows no mercy to those who threaten her people. She earned her name by killing three settler scouts with just a knife in a moonless night. Warriors compete for the honor of joining her raids.',
        personality: 'Cunning and ruthless in combat. Protective of her warriors. Strategic mind with deadly execution.',
        faction: 'NAHI_COALITION',
        dialogue: [
          'My raids strike fear into settler hearts. This is good. Fear keeps them off our lands.',
          'I do not lead warriors. I lead wolves. We hunt together, we kill together, we survive together.',
          'Red Thunder plans the war. I plan the raids. Gray Wolf worries about both. This is how we function.',
          'You want to raid with me? Prove you can move silent, strike fast, and leave no trace. Otherwise, stay home.',
        ],
        quests: ['raid_mission', 'stealth_training', 'night_strike'],
      },
      {
        id: 'thunder-speaker',
        name: 'Thunder Speaker',
        title: 'War Shaman',
        description: 'A warrior who walks between the physical and spiritual worlds. He blesses weapons, performs war rituals, and calls upon the spirits to protect Coalition fighters. His face paint is said to be blessed by Wise Sky, and warriors who carry his tokens claim they cannot be killed in battle.',
        personality: 'Mystical and intense. Believes the spirits guide every battle. Performs rituals that terrify enemies.',
        faction: 'NAHI_COALITION',
        dialogue: [
          'The warrior spirits watch over us. They guide our blades and shield us from harm. But only if we honor them properly.',
          'I paint your face for war. Each mark is a prayer, each color a protection. Wear them with pride and fight with honor.',
          'The settlers fear our war cries. Good. Their fear feeds the spirits and strengthens our warriors.',
          'Wise Sky communes with all spirits. I commune only with those who love battle. We serve the same people, but different powers.',
        ],
        quests: ['spirit_weapon', 'war_blessing', 'ritual_combat'],
      },
      {
        id: 'broken-lance',
        name: 'Broken Lance',
        title: 'Weapon Master',
        description: 'An older warrior who can no longer fight in raids due to a leg injury, but whose knowledge of weapons is unmatched. He crafts traditional Nahi weapons and teaches their use. His workshop contains everything from stone knives to captured settler firearms that he has adapted for Coalition use.',
        personality: 'Gruff but passionate about his craft. Takes pride in every weapon made. Bitter about his injury but channels it into teaching.',
        faction: 'NAHI_COALITION',
        dialogue: [
          'My fighting days ended when a settler bullet shattered my leg. But I still serve the Coalition with every weapon I forge.',
          'Each weapon I create carries the skill of my hands and the prayers of Thunder Speaker. They are more than tools. They are extensions of the warrior spirit.',
          'You want a weapon? Earn it. Complete my trials, prove your worth, and I will craft something worthy of your hand.',
          'The settlers have factories. We have master craftsmen. Their weapons are many. Ours are perfect.',
        ],
        quests: ['weapon_trial', 'master_weapon_request'],
        isVendor: true,
        shopId: 'warrior_weapons_shop',
      },
      {
        id: 'running-deer',
        name: 'Running Deer',
        title: 'Scout Leader',
        description: 'A young but exceptionally talented scout who can track anything across any terrain. She trains Coalition scouts in the arts of stealth, tracking, and survival. Her intelligence reports have saved countless lives by warning of incoming threats.',
        personality: 'Observant and patient. Teaches through experience. Values intelligence over brute force.',
        faction: 'NAHI_COALITION',
        dialogue: [
          'The best warrior is the one the enemy never sees. Learn to move like the wind - felt but not seen.',
          'I track settler patrols, Frontera movements, even individual outlaws. Nothing crosses Coalition lands without me knowing.',
          'She-Wolf leads the raids. I tell her where to raid, when to strike, and how to escape. We are the blade and the eyes.',
          'You think you can track? Follow me for one day. If you can keep up and stay silent, I will teach you.',
        ],
        quests: ['scout_training', 'tracking_mission', 'reconnaissance'],
      },
      {
        id: 'white-hawk',
        name: 'White Hawk',
        title: 'Young Warrior',
        description: 'An eager young warrior desperate to prove himself worthy of joining Red Thunder\'s inner circle. He trains harder than anyone, volunteers for the most dangerous missions, and idolizes the legendary fighters. His enthusiasm sometimes outpaces his wisdom.',
        personality: 'Enthusiastic and brave, sometimes reckless. Eager to please. Learning to balance courage with caution.',
        faction: 'NAHI_COALITION',
        dialogue: [
          'I will be the greatest warrior the Coalition has ever seen! Iron Fist says I have potential.',
          'She-Wolf took me on a raid last moon. I killed my first settler scout. It was... different than I imagined.',
          'My father wants me on the Council. I belong here, with the warriors. This is where I can truly serve our people.',
          'Red Thunder barely knows my name. But he will. I will make him notice me.',
        ],
        quests: ['prove_yourself', 'first_raid'],
      },
    ],
    availableActions: ['combat-training', 'sparring', 'war-council', 'weapon-practice', 'ritual-preparation', 'join-raid'],
    availableCrimes: ['Steal Sacred Weapon', 'Sabotage Training'],
    jobs: [
      {
        id: 'basic_warrior_training',
        name: 'Basic Warrior Training',
        description: 'Train with Iron Fist in fundamental combat techniques. Brutal, exhausting, and essential for any warrior.',
        energyCost: 20,
        cooldownMinutes: 60,
        rewards: { goldMin: 30, goldMax: 50, xp: 70, items: ['warrior_badge'] },
        requirements: { minLevel: 8 },
      },
      {
        id: 'advanced_combat',
        name: 'Advanced Combat Training',
        description: 'Elite training for experienced warriors. Iron Fist holds nothing back. Prepare to bleed and learn.',
        energyCost: 30,
        cooldownMinutes: 120,
        rewards: { goldMin: 60, goldMax: 95, xp: 140, items: ['combat_mastery_token', 'healing_herbs'] },
        requirements: { minLevel: 15 },
      },
      {
        id: 'scout_training_mission',
        name: 'Scout Training Exercise',
        description: 'Learn stealth, tracking, and reconnaissance from Running Deer. Silent movement and sharp eyes required.',
        energyCost: 25,
        cooldownMinutes: 90,
        rewards: { goldMin: 45, goldMax: 75, xp: 110, items: ['scout_badge', 'tracking_knowledge'] },
        requirements: { minLevel: 10 },
      },
      {
        id: 'raid_participation',
        name: 'Join She-Wolf\'s Raid',
        description: 'Participate in a Coalition raid against enemy positions. High danger, high reward. Only for proven warriors.',
        energyCost: 40,
        cooldownMinutes: 240,
        rewards: { goldMin: 100, goldMax: 170, xp: 220, items: ['raid_trophy', 'ceremonial_token', 'captured_goods'] },
        requirements: { minLevel: 18 },
      },
      {
        id: 'weapon_crafting_assist',
        name: 'Weapon Crafting Assistance',
        description: 'Help Broken Lance in his workshop. Learn the sacred art of weapon-making while assisting a master craftsman.',
        energyCost: 15,
        cooldownMinutes: 75,
        rewards: { goldMin: 35, goldMax: 60, xp: 85, items: ['crafting_knowledge', 'weapon_parts'] },
        requirements: { minLevel: 12 },
      },
      {
        id: 'war_ritual',
        name: 'War Ritual Participation',
        description: 'Participate in Thunder Speaker\'s war rituals. Receive spiritual blessings and commune with warrior spirits.',
        energyCost: 20,
        cooldownMinutes: 180,
        rewards: { goldMin: 40, goldMax: 70, xp: 120, items: ['spirit_blessing', 'war_paint', 'sacred_token'] },
        requirements: { minLevel: 14 },
      },
      {
        id: 'elite_mission',
        name: 'Elite Warrior Mission',
        description: 'Special operations assigned only to the most skilled warriors. Red Thunder himself approves these missions.',
        energyCost: 50,
        cooldownMinutes: 360,
        rewards: { goldMin: 150, goldMax: 250, xp: 300, items: ['red_thunder_commendation', 'legendary_weapon', 'sacred_artifact'] },
        requirements: { minLevel: 25 },
      },
    ],
    shops: [
      {
        id: 'warrior_weapons_shop',
        name: 'Broken Lance\'s Arsenal',
        description: 'Traditional Nahi weapons and captured settler arms, all modified and blessed for Coalition warriors. Trade with ceremonial tokens, pelts, or prove your worth.',
        shopType: 'weapons',
        items: [
          { itemId: 'nahi_war_axe', name: 'Nahi War Axe', description: 'Traditional war axe blessed by Thunder Speaker. Deadly in close combat. [Barter: 5 ceremonial tokens]', price: 0, requiredLevel: 10 },
          { itemId: 'spirit_knife', name: 'Spirit Knife', description: 'Blade forged with spiritual rituals. Never dulls, never breaks. [Barter: 8 ceremonial tokens]', price: 0, requiredLevel: 12 },
          { itemId: 'coalition_bow', name: 'Coalition War Bow', description: 'Powerful composite bow. Silent death from distance. [Barter: 6 ceremonial tokens + 3 wolf pelts]', price: 0, requiredLevel: 11 },
          { itemId: 'tomahawk_blessed', name: 'Blessed Tomahawk', description: 'Throwing axe blessed for accuracy and lethality. [Barter: 4 ceremonial tokens]', price: 0, requiredLevel: 9 },
          { itemId: 'war_shield', name: 'Nahi War Shield', description: 'Reinforced hide shield adorned with protective symbols. [Barter: 7 ceremonial tokens]', price: 0, requiredLevel: 13 },
          { itemId: 'modified_rifle', name: 'Modified Settler Rifle', description: 'Captured rifle modified by Broken Lance. Best of both worlds. [Barter: 12 ceremonial tokens + rare herbs]', price: 0, requiredLevel: 16 },
          { itemId: 'war_paint_set', name: 'War Paint Set', description: 'Sacred paints blessed by Thunder Speaker. Grants courage in battle. [Barter: 3 ceremonial tokens]', price: 0, requiredLevel: 8 },
          { itemId: 'warrior_armor', name: 'Warrior\'s Armor', description: 'Leather armor reinforced with bone and blessed hide. Protection with mobility. [Barter: 10 ceremonial tokens + bear pelt]', price: 0, requiredLevel: 15 },
        ],
        buyMultiplier: 0.4,
      },
    ],
    secrets: [
      {
        id: 'legendary_weapons_vault',
        name: 'Vault of Legendary Weapons',
        description: 'Hidden deep within the Warrior Society Hall lies a vault containing legendary weapons from Coalition history - blades wielded by great chiefs, bows that never missed, shields that turned aside bullets. These weapons are kept for dire need, when the Coalition\'s very survival is at stake.',
        type: 'hidden_room',
        unlockCondition: {
          minReputation: 85,
          npcTrust: { npcId: 'red-thunder', level: 5 },
        },
        content: {
          actions: ['view_legendary_weapons', 'request_sacred_arm', 'learn_weapon_history'],
          npcs: [],
          dialogue: [
            '"You have proven yourself worthy of our highest trust. These weapons carry the spirits of our greatest warriors. To wield one is to carry their legacy. Choose wisely, fight honorably, and return it when the battle is won. These are not trophies. They are sacred trusts."',
          ],
        },
      },
      {
        id: 'secret_war_plans',
        name: 'Inner War Council Chamber',
        description: 'A concealed chamber where Red Thunder, She-Wolf, and Gray Wolf plan their most sensitive military operations. Maps show settler patrol routes, weak points in fort defenses, and planned raid targets. Access is granted only to those Red Thunder trusts with Coalition survival.',
        type: 'progressive',
        unlockCondition: {
          minReputation: 75,
          npcTrust: { npcId: 'she-wolf', level: 4 },
        },
        content: {
          actions: ['access_war_plans', 'propose_raid_target', 'coordinate_offensive'],
          npcs: [],
          dialogue: [
            '"She-Wolf speaks for you. Red Thunder has approved your presence. What you see here determines the fate of our people. We plan not just raids, but the future of the Coalition. Speak your thoughts, but speak them carefully. Lives depend on every decision we make."',
          ],
        },
      },
    ],
    connections: [],
    dangerLevel: 5,
    factionInfluence: { settlerAlliance: 0, nahiCoalition: 98, frontera: 2 },
    isUnlocked: true,
    isHidden: false,
  },

  // ============================================================
  // 11. BARTER TRADING POST - Phase 1, Wave 1.2
  // ============================================================
  {
    _id: KAIOWA_MESA_BUILDING_IDS.BARTER_TRADING_POST,
    name: 'Coalition Barter Exchange',
    description: 'A bustling marketplace where the Coalition\'s barter economy thrives without a single gold coin changing hands. Pelts hang from rafters, herbs bundle on tables, and craftsmen display their finest work. Traders from across the territory come here to exchange goods, services, and ceremonial tokens. Sky Trader presides over fair exchanges, while artisans create goods that fetch high value in barter. The air smells of tanned leather, sage, and the sweet smoke of curing meats.',
    shortDescription: 'Barter-based marketplace and artisan center',
    type: 'trading_post',
    region: 'town',
    parentId: LOCATION_IDS.KAIOWA_MESA,
    tier: 5,
    dominantFaction: 'nahi',
    operatingHours: { open: 7, close: 20 },
    atmosphere: 'Pelts and hides hang from every rafter. Tables overflow with herbs, crafts, and trade goods. The constant hum of negotiation fills the air as traders haggle over fair exchanges. No gold here - only goods, favors, and ceremonial tokens.',
    npcs: [
      {
        id: 'sky-trader',
        name: 'Sky Trader',
        title: 'Master of Exchange',
        description: 'A sharp-eyed woman who can assess the value of anything in seconds. She has memorized exchange rates for hundreds of items and ensures every trade is fair. She works closely with Black Elk to manage the Coalition\'s barter economy, and her word on value is considered final. No one cheats Sky Trader - those who try find themselves banned from the exchange.',
        personality: 'Sharp, fair, and absolutely incorruptible. Values honest trade above all. Remembers every transaction.',
        faction: 'NAHI_COALITION',
        dialogue: [
          'Gold is the settlers\' weakness. They fight over it, kill for it, destroy for it. We trade in trust and value. Much stronger.',
          'Three wolf pelts equal one ceremonial token. One token equals a day of skilled labor. A master craftsman\'s work? Priceless, but we negotiate.',
          'Silver Moon handles small trades. I handle the exchanges that affect the entire Coalition. Bring me quality, and I will find you what you need.',
          'Black Elk sets policy. I execute it. Together, we keep the Coalition prosperous without surrendering to gold.',
        ],
        quests: ['barter_network', 'trade_route', 'rare_exchange'],
        isVendor: true,
        shopId: 'barter_goods_shop',
      },
      {
        id: 'three-rivers',
        name: 'Three Rivers',
        title: 'Traveling Merchant',
        description: 'A charismatic trader who travels between Coalition settlements, Frontera towns, and even some settler communities. He brings exotic goods, rare items, and news from distant places. His pack is always full of surprises, and his stories are even more valuable than his trade goods.',
        personality: 'Charming and worldly. Knows everyone and everything. Values interesting stories as much as valuable goods.',
        faction: 'NAHI_COALITION',
        dialogue: [
          'I have walked from the northern mountains to the Frontera border. Every step taught me something new to trade.',
          'You need something rare? Give me time. I know someone who knows someone who has what you seek.',
          'The settlers trade for gold. The Frontera trade for revolution. We trade for survival and community. I know which system will last.',
          'I bring news as well as goods. Did you hear what happened in Red Gulch? No? Sit, let me tell you...',
        ],
        quests: ['exotic_acquisition', 'distant_trade'],
        isVendor: true,
        shopId: 'exotic_goods_shop',
      },
      {
        id: 'weaving-hands',
        name: 'Weaving Hands',
        title: 'Master Artisan',
        description: 'An elderly woman whose woven blankets and baskets are considered the finest in the territory. Her work is so valued that settlers will trade gold for her pieces, which she then converts to goods the Coalition needs. She teaches the next generation of artisans, ensuring the craft traditions survive.',
        personality: 'Patient and wise. Takes immense pride in her craft. Believes art preserves culture.',
        faction: 'NAHI_COALITION',
        dialogue: [
          'Each thread I weave carries the stories of my grandmothers. This is not just craft. This is memory.',
          'Settlers pay gold for my blankets. I trade that gold for rifles and medicine. Beauty becomes protection. This is the power of art.',
          'Sky Trader values my work highly. One of my ceremonial blankets can fetch twenty tokens. But I only make them for those who will honor them.',
          'You wish to learn? Good. Sit. Watch. Listen. Art cannot be rushed.',
        ],
        quests: ['artisan_apprenticeship', 'masterwork_commission'],
      },
      {
        id: 'wolf-hunter',
        name: 'Wolf Hunter',
        title: 'Fur Trader',
        description: 'A grizzled hunter who supplies the Exchange with premium pelts - wolf, bear, elk, and rare mountain lion. His furs are the standard for high-value barter trades. He knows every hunting ground in Coalition territory and guards his best spots jealously.',
        personality: 'Solitary and straightforward. Respects skill, dislikes waste. More comfortable with animals than people.',
        faction: 'NAHI_COALITION',
        dialogue: [
          'A perfect wolf pelt takes patience, skill, and respect for the animal. Rush the kill, ruin the hide.',
          'Sky Trader pays fair rates for quality. Three prime wolf pelts equal one ceremonial token. Damaged pelt? Half value.',
          'I hunt alone. The best hunting grounds are secrets I earned through years of tracking. Want to learn? Prove you can keep pace.',
          'Settlers trap with steel jaws that ruin pelts. We hunt with respect and skill. Our furs are worth double theirs.',
        ],
        quests: ['hunting_expedition', 'legendary_pelt'],
      },
      {
        id: 'bright-feather',
        name: 'Bright Feather',
        title: 'Herbalist Trader',
        description: 'A young woman who gathers and trades medicinal herbs, ceremonial plants, and rare botanicals. She works closely with Healing Hand but focuses on trade rather than healing. Her herb bundles are essential for medicine, rituals, and even some barter exchanges.',
        personality: 'Energetic and knowledgeable. Passionate about plants. Loves teaching others about herb lore.',
        faction: 'NAHI_COALITION',
        dialogue: [
          'Every plant has value if you know how to use it. This sage purifies, that root heals, those flowers bring visions.',
          'Healing Hand teaches medicine. I teach value. A bundle of rare healing herbs can trade for a ceremonial token.',
          'I gather at dawn when the plants are most potent. Join me sometime - I will show you which herbs are worth your time.',
          'Settlers dismiss our herbs as primitive medicine. Then they pay gold when their doctors fail. I keep raising my prices.',
        ],
        quests: ['herb_gathering', 'rare_botanical'],
      },
      {
        id: 'stone-carver',
        name: 'Stone Carver',
        title: 'Token Maker',
        description: 'The craftsman who creates the ceremonial tokens that serve as the Coalition\'s high-value currency. Each token is individually carved with sacred symbols and blessed by Thunder Speaker. His workshop is heavily guarded, and the secrets of token-making are passed only to chosen apprentices.',
        personality: 'Secretive and serious. Views his work as sacred duty. Guards his craft zealously.',
        faction: 'NAHI_COALITION',
        dialogue: [
          'Each token I carve represents trust earned, service given, or value provided. They cannot be counterfeited. I make sure of that.',
          'I craft perhaps fifty tokens per moon cycle. No more. Scarcity maintains value. This is the foundation of our economy.',
          'Thunder Speaker blesses every token I make. They are not just currency. They are sacred objects that represent honor.',
          'You want to learn token-making? First, prove you can keep secrets. Then prove you can be trusted. Then we talk.',
        ],
        quests: ['token_crafting_trial', 'sacred_commission'],
      },
    ],
    availableActions: ['barter-trade', 'examine-goods', 'commission-craft', 'request-exotic', 'exchange-tokens', 'trade-route-info'],
    availableCrimes: ['Steal Trade Goods', 'Counterfeit Token', 'Cheat in Trade'],
    jobs: [
      {
        id: 'trade_assistance',
        name: 'Trade Assistance',
        description: 'Help Sky Trader evaluate goods, facilitate exchanges, and maintain the marketplace. Learn the art of fair barter.',
        energyCost: 15,
        cooldownMinutes: 60,
        rewards: { goldMin: 25, goldMax: 45, xp: 60, items: ['trade_knowledge', 'barter_goods'] },
        requirements: { minLevel: 5 },
      },
      {
        id: 'hunting_for_pelts',
        name: 'Hunting Expedition',
        description: 'Join Wolf Hunter on a hunting expedition for valuable pelts. Requires skill, patience, and respect for the prey.',
        energyCost: 30,
        cooldownMinutes: 150,
        rewards: { goldMin: 60, goldMax: 100, xp: 130, items: ['wolf_pelt', 'elk_hide', 'ceremonial_token'] },
        requirements: { minLevel: 12 },
      },
      {
        id: 'herb_gathering_trade',
        name: 'Herb Gathering for Trade',
        description: 'Gather rare medicinal and ceremonial herbs with Bright Feather. Dawn departures, full day expeditions.',
        energyCost: 20,
        cooldownMinutes: 90,
        rewards: { goldMin: 35, goldMax: 65, xp: 85, items: ['healing_herbs', 'ceremonial_herbs', 'rare_botanical'] },
        requirements: { minLevel: 8 },
      },
      {
        id: 'artisan_helper',
        name: 'Artisan\'s Assistant',
        description: 'Assist Weaving Hands in creating trade goods. Learn traditional crafts while producing valuable barter items.',
        energyCost: 25,
        cooldownMinutes: 120,
        rewards: { goldMin: 45, goldMax: 80, xp: 110, items: ['crafted_goods', 'artisan_token'] },
        requirements: { minLevel: 10 },
      },
      {
        id: 'trade_caravan',
        name: 'Trade Caravan Escort',
        description: 'Escort Three Rivers on a dangerous trade route to distant settlements. Protection and negotiation skills required.',
        energyCost: 40,
        cooldownMinutes: 240,
        rewards: { goldMin: 90, goldMax: 150, xp: 180, items: ['exotic_goods', 'ceremonial_token', 'distant_favor'] },
        requirements: { minLevel: 16 },
      },
      {
        id: 'token_delivery',
        name: 'Ceremonial Token Delivery',
        description: 'Transport newly crafted ceremonial tokens to other Coalition settlements. High value cargo requires trusted couriers.',
        energyCost: 25,
        cooldownMinutes: 180,
        rewards: { goldMin: 70, goldMax: 110, xp: 140, items: ['courier_payment', 'trust_bonus'] },
        requirements: { minLevel: 14 },
      },
      {
        id: 'masterwork_trade',
        name: 'Masterwork Trade Negotiation',
        description: 'Facilitate high-value exchanges involving masterwork crafts, rare artifacts, and exotic goods. For experienced traders only.',
        energyCost: 35,
        cooldownMinutes: 300,
        rewards: { goldMin: 120, goldMax: 200, xp: 220, items: ['master_trader_token', 'rare_artifact', 'sky_trader_favor'] },
        requirements: { minLevel: 20 },
      },
    ],
    shops: [
      {
        id: 'barter_goods_shop',
        name: 'General Barter Exchange',
        description: 'Standard trade goods available for barter. Pelts, herbs, crafted items, and ceremonial tokens accepted.',
        shopType: 'general',
        items: [
          { itemId: 'wolf_pelt', name: 'Wolf Pelt', description: 'Premium pelt. [Barter: hunting services or equivalent goods]', price: 0 },
          { itemId: 'elk_hide', name: 'Elk Hide', description: 'Large hide for crafting. [Barter: 2 days labor or 1 ceremonial token]', price: 0 },
          { itemId: 'bear_pelt', name: 'Bear Pelt', description: 'Rare and valuable. [Barter: 3 ceremonial tokens or masterwork trade]', price: 0, requiredLevel: 15 },
          { itemId: 'healing_herb_bundle', name: 'Healing Herb Bundle', description: 'Medicinal herbs. [Barter: 1 pelt or services rendered]', price: 0 },
          { itemId: 'ceremonial_herbs', name: 'Ceremonial Herb Bundle', description: 'Rare ritual herbs. [Barter: 2 ceremonial tokens]', price: 0, requiredLevel: 10 },
          { itemId: 'woven_blanket', name: 'Woven Blanket', description: 'Weaving Hands\' work. [Barter: 4 ceremonial tokens]', price: 0, requiredLevel: 8 },
          { itemId: 'ceremonial_basket', name: 'Ceremonial Basket', description: 'Artisan craft. [Barter: 2 ceremonial tokens]', price: 0 },
          { itemId: 'leather_goods', name: 'Quality Leather Goods', description: 'Belts, pouches, straps. [Barter: 1 ceremonial token or pelts]', price: 0 },
        ],
        buyMultiplier: 0.0, // Barter only
      },
      {
        id: 'exotic_goods_shop',
        name: 'Three Rivers Exotic Goods',
        description: 'Rare items from distant lands. High-value barter only.',
        shopType: 'specialty',
        items: [
          { itemId: 'frontier_spices', name: 'Frontier Spices', description: 'From Frontera territory. [Barter: 3 ceremonial tokens]', price: 0, requiredLevel: 10 },
          { itemId: 'mountain_jade', name: 'Mountain Jade', description: 'Carved stone from northern tribes. [Barter: 5 ceremonial tokens + rare pelt]', price: 0, requiredLevel: 15 },
          { itemId: 'spirit_crystal', name: 'Spirit Crystal', description: 'Mystical stone. [Barter: 8 ceremonial tokens or equivalent masterwork]', price: 0, requiredLevel: 18 },
          { itemId: 'ancient_artifact', name: 'Ancient Tribal Artifact', description: 'Historical relic. [Barter: negotiated with Sky Trader]', price: 0, requiredLevel: 20 },
          { itemId: 'exotic_weapon', name: 'Exotic Weapon', description: 'From distant lands. [Barter: 10 ceremonial tokens]', price: 0, requiredLevel: 16 },
          { itemId: 'rare_medicine', name: 'Rare Medicine', description: 'Unknown to local healers. [Barter: 6 ceremonial tokens]', price: 0, requiredLevel: 12 },
        ],
        buyMultiplier: 0.0, // Barter only
      },
    ],
    secrets: [
      {
        id: 'token_workshop',
        name: 'Sacred Token Workshop',
        description: 'Stone Carver\'s hidden workshop where ceremonial tokens are crafted. The techniques are ancient secrets, and the tools themselves are considered sacred. Only the most trusted are permitted to witness the creation of tokens that power the Coalition\'s entire economy.',
        type: 'hidden_room',
        unlockCondition: {
          minReputation: 75,
          npcTrust: { npcId: 'sky-trader', level: 4 },
        },
        content: {
          actions: ['observe_token_crafting', 'learn_sacred_techniques', 'commission_special_token'],
          npcs: [],
          dialogue: [
            '"Sky Trader vouches for you. Stone Carver will show you how our tokens are made - how we maintain value without gold, trust without banks. This knowledge is the foundation of Coalition independence. Guard it as you would guard our people\'s lives."',
          ],
        },
      },
      {
        id: 'hidden_trade_routes',
        name: 'Secret Trade Network',
        description: 'Three Rivers maintains covert trade routes that bypass settler checkpoints and reach into Frontera territory, distant Nahi settlements, and even sympathetic settler communities. These routes keep the Coalition supplied even during conflicts, and the knowledge of them is worth more than gold.',
        type: 'progressive',
        unlockCondition: {
          minReputation: 70,
          npcTrust: { npcId: 'three-rivers', level: 5 },
        },
        content: {
          actions: ['access_secret_routes', 'underground_trade', 'smuggling_network'],
          npcs: [],
          dialogue: [
            '"You have proven yourself trustworthy and capable. I will show you the hidden paths - the routes that keep our people fed when the settlers blockade us, armed when they embargo us, and prosperous when they try to starve us. But know this: reveal these routes, and you condemn the Coalition to dependency on settler mercy. And they have no mercy."',
          ],
        },
      },
    ],
    connections: [],
    dangerLevel: 2,
    factionInfluence: { settlerAlliance: 10, nahiCoalition: 85, frontera: 15 },
    isUnlocked: true,
    isHidden: false,
  },
];

/**
 * Seed Kaiowa Mesa buildings into the database
 */
export async function seedKaiowaMesaBuildings(): Promise<void> {
  try {
    // Verify Kaiowa Mesa exists
    const kaiowaMesa = await Location.findById(LOCATION_IDS.KAIOWA_MESA);
    if (!kaiowaMesa) {
      console.warn('Warning: Kaiowa Mesa location not found. Buildings will reference non-existent parent.');
    }

    // Delete existing Kaiowa Mesa buildings (by parentId)
    await Location.deleteMany({ parentId: LOCATION_IDS.KAIOWA_MESA });

    // Insert Kaiowa Mesa buildings
    await Location.insertMany(kaiowaMesaBuildings);

    console.log(`Successfully seeded ${kaiowaMesaBuildings.length} Kaiowa Mesa buildings`);
  } catch (error) {
    logger.error('Error seeding Kaiowa Mesa buildings', { error: error instanceof Error ? error.message : error });
    throw error;
  }
}

export default kaiowaMesaBuildings;
